import { BrandMark } from "@/components/BrandMark";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ChevronLeft, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

const securityImage = "/manus-storage/amarktai-ai-master-hero_5b3a2d3c.png";

export default function Auth() {
  const mode = trpc.auth.mode.useQuery();
  return <main className="grid min-h-screen bg-[#F7FAFF] lg:grid-cols-[1fr_.88fr]"><section className="relative flex min-h-[500px] flex-col overflow-hidden bg-white p-6 sm:p-10 lg:min-h-screen lg:p-14"><div className="absolute -left-44 top-40 size-[520px] rounded-full bg-[#E7F0FF] blur-3xl"/><div className="relative flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-1 text-sm font-bold text-[#52729E] transition hover:text-[#1463F3]"><ChevronLeft size={17}/>Back to home</Link><BrandMark/></div><div className="relative mt-auto max-w-xl pt-24 lg:pt-0"><p className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.15em] text-[#1463F3]"><ShieldCheck size={14}/>Protected by design</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.88] tracking-[-.08em] text-[#08255C] sm:text-7xl">The sales workspace, protected.</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#59769E]">Amarktai AI keeps operational context, review actions and integration controls behind a secure organisation sign-in and email second factor.</p><div className="mt-8 grid gap-3 text-sm font-semibold text-[#48668E]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#1463F3]"/>Workspace data stays under authenticated access.</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#1463F3]"/>Every intended action has an audit trail.</span></div></div><div className="pointer-events-none absolute -bottom-10 right-[-2rem] w-[44%] min-w-[245px] opacity-90"><img src={securityImage} alt="" className="w-full"/></div></section><section className="grid place-items-center bg-[#0A2C69] p-5 sm:p-10"><div className="w-full max-w-md rounded-[2rem] border border-white/20 bg-white p-7 shadow-[0_28px_65px_rgba(0,0,0,.25)] sm:p-10"><div className="grid size-12 place-items-center rounded-2xl bg-[#EAF2FF] text-[#1463F3]"><LockKeyhole size={20}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.15em] text-[#1463F3]">Secure sign-in</p><h2 className="mt-3 font-display text-5xl font-bold leading-[.9] tracking-[-.075em] text-[#08255C]">Open your workspace.</h2>{mode.isLoading ? <p className="mt-5 text-sm text-[#5B769E]">Loading sign-in…</p> : mode.data?.local ? <LocalLoginForm/> : <ManagedSignIn/>}</div></section></main>;
}

function ManagedSignIn() { return <><p className="mt-5 text-sm leading-6 text-[#5A769F]">Continue to your protected identity flow. Once authenticated, you can access the command centre, agent desk, workflow studio, knowledge and connections.</p><button onClick={() => startLogin()} className="mt-8 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1463F3] text-sm font-bold text-white shadow-[0_10px_22px_rgba(20,99,243,.22)] transition hover:-translate-y-0.5 hover:bg-[#0A4FD2] active:scale-[.98]">Continue securely <ArrowRight size={17}/></button><SecurityFineprint/></>; }
function LocalLoginForm() { const [, navigate] = useLocation(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const login = trpc.auth.localLogin.useMutation({ onSuccess: () => { toast.success("Signed in. Complete the email verification step to enter the workspace."); navigate("/workspace"); }, onError: error => toast.error(error.message) }); return <form onSubmit={event => { event.preventDefault(); login.mutate({ email, password }); }} className="mt-6 grid gap-4"><div><label htmlFor="email" className="text-sm font-bold text-[#08255C]">Administrator email</label><input id="email" type="email" autoComplete="email" required value={email} onChange={event => setEmail(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#CFE0F8] px-3 outline-none transition focus:border-[#1463F3]"/></div><div><label htmlFor="password" className="text-sm font-bold text-[#08255C]">Password</label><input id="password" type="password" autoComplete="current-password" required minLength={12} value={password} onChange={event => setPassword(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-[#CFE0F8] px-3 outline-none transition focus:border-[#1463F3]"/></div><button type="submit" disabled={login.isPending} className="mt-3 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1463F3] text-sm font-bold text-white shadow-[0_10px_22px_rgba(20,99,243,.22)] transition hover:-translate-y-0.5 hover:bg-[#0A4FD2] active:scale-[.98]">{login.isPending ? "Signing in…" : "Sign in securely"}<ArrowRight size={17}/></button><SecurityFineprint/></form>; }
function SecurityFineprint() { return <p className="mt-7 text-center text-xs leading-5 text-[#7290B8]"><Sparkles className="mr-1 inline size-3"/>Credentials and integration secrets remain server-side.</p>; }
