import { BrandMark } from "@/components/BrandMark";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ChevronLeft, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

const securityImage = "/manus-storage/amarktai-ai-trust-security_8b827cc4.png";

export default function Auth() {
  const mode = trpc.auth.mode.useQuery();
  return <main className="relative grid min-h-screen overflow-hidden bg-[#071326] text-[#F5F7FB] lg:grid-cols-[1.03fr_.97fr]">
    <div className="pointer-events-none absolute -left-40 top-24 size-[600px] rounded-full bg-[#1B64F2]/20 blur-[130px]"/>
    <section className="relative z-10 flex min-h-[500px] flex-col border-b border-white/10 p-6 sm:p-10 lg:min-h-screen lg:border-b-0 lg:border-r lg:border-white/10 lg:p-14">
      <div className="flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-1 text-sm font-bold text-[#A9BFDF] transition hover:text-white"><ChevronLeft size={17}/>Back to site</Link><BrandMark/></div>
      <div className="mt-auto max-w-xl pt-24 lg:pt-0"><p className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.15em] text-[#8CB7FF]"><ShieldCheck size={14}/>Private operations access</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.86] tracking-[-.08em] sm:text-7xl">The operational view, protected.</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#A9BFDF]">Amarktai Network keeps sales context, review decisions, workload and audit evidence behind a protected local workspace and a second verification layer.</p><div className="mt-8 grid gap-3 text-sm font-semibold text-[#C8D8F2]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#70A2FF]"/>Operational data remains access controlled.</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#70A2FF]"/>Action history stays connected to each decision.</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#70A2FF]"/>Every external action remains review-first.</span></div></div>
      <div className="pointer-events-none absolute bottom-8 right-[-3rem] w-[37%] min-w-[230px] opacity-70"><img src={securityImage} alt="" className="w-full rounded-3xl"/></div>
    </section>
    <section className="relative z-10 grid place-items-center p-5 sm:p-10"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-[#0C1E3E]/95 p-7 shadow-[0_28px_70px_rgba(0,0,0,.38)] backdrop-blur sm:p-10"><div className="grid size-12 place-items-center rounded-2xl border border-[#4D82E7]/30 bg-[#123467] text-[#9ABEFF]"><LockKeyhole size={20}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.15em] text-[#8CB7FF]">Amarktai Network workspace</p><h2 className="mt-3 font-display text-5xl font-bold leading-[.9] tracking-[-.075em]">Open operations.</h2>{mode.isLoading ? <p className="mt-5 text-sm text-[#A9BFDF]">Loading secure workspace access…</p> : mode.data?.local ? <LocalLoginForm/> : mode.data?.developmentPreview ? <DevelopmentPreviewLogin/> : <LocalLoginSetup/>}</div></section>
  </main>;
}

function LocalLoginSetup() { return <div className="mt-6 rounded-2xl border border-[#3D69AD]/35 bg-[#0A1C39] p-5"><p className="text-sm font-bold text-white">Local workspace access is not configured yet.</p><p className="mt-2 text-sm leading-6 text-[#A9BFDF]">This product uses Amarktai Network email-and-password access. Enable it with <code className="rounded bg-white/10 px-1.5 py-0.5 text-[#DCE8FA]">AUTH_MODE=local</code> and set the initial administrator credentials during Webdock installation. No external identity redirect is used here.</p><div className="mt-4 rounded-xl border border-white/10 bg-white/[.035] p-3 text-xs leading-5 text-[#9DB6D8]">After configuration, return to this page, sign in with the administrator email and password, then complete the email verification step before entering the dashboard.</div><Fineprint/></div>; }

function DevelopmentPreviewLogin() { const [, navigate] = useLocation(); const login = trpc.auth.developmentPreviewLogin.useMutation({ onSuccess: () => { toast.success("Development dashboard preview opened."); navigate("/dashboard"); }, onError: error => toast.error(error.message) }); return <div className="mt-6"><p className="text-sm leading-6 text-[#A9BFDF]">Open the protected interface with a disposable development session. It contains no production credentials, is unavailable after deployment, and does not replace the Webdock sign-in process.</p><button onClick={() => login.mutate()} disabled={login.isPending} className="mt-7 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white shadow-[0_10px_25px_rgba(27,100,242,.28)] transition hover:-translate-y-0.5 hover:bg-[#2B76FF] active:scale-[.98]">{login.isPending ? "Opening preview…" : "Open dashboard preview"}<ArrowRight size={17}/></button><Fineprint/></div>; }

function LocalLoginForm() {
  const [, navigate] = useLocation();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const login = trpc.auth.localLogin.useMutation({ onSuccess: () => { toast.success("Signed in. Complete access verification to enter operations."); navigate("/dashboard"); }, onError: error => toast.error(error.message) });
  return <form onSubmit={event => { event.preventDefault(); login.mutate({ email, password }); }} className="mt-6 grid gap-4"><p className="text-sm leading-6 text-[#A9BFDF]">Use the administrator email and password configured for this Amarktai Network workspace.</p><div><label htmlFor="email" className="text-sm font-bold text-[#DCE8FA]">Administrator email</label><input id="email" type="email" autoComplete="email" required value={email} onChange={event => setEmail(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none transition placeholder:text-[#607EA8] focus:border-[#4E8BFF]"/></div><div><label htmlFor="password" className="text-sm font-bold text-[#DCE8FA]">Password</label><input id="password" type="password" autoComplete="current-password" required minLength={12} value={password} onChange={event => setPassword(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none transition placeholder:text-[#607EA8] focus:border-[#4E8BFF]"/></div><button type="submit" disabled={login.isPending} className="mt-3 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white shadow-[0_10px_25px_rgba(27,100,242,.28)] transition hover:-translate-y-0.5 hover:bg-[#2B76FF] active:scale-[.98]">{login.isPending ? "Signing in…" : "Enter operations"}<ArrowRight size={17}/></button><Fineprint/></form>;
}

function Fineprint() { return <p className="mt-7 text-center text-xs leading-5 text-[#7693BB]">Credentials and connection secrets remain on the server.</p>; }
