import { BrandMark } from "@/components/BrandMark";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ChevronLeft, LockKeyhole, ShieldCheck, UserPlus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link, useLocation } from "wouter";

const securityImage = "/assets/amarktai-sales-security.svg";

export default function Auth() {
  const mode = trpc.auth.mode.useQuery();
  const invite = typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("invite") : null;
  const query = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams();
  const reset = query.get("reset"); const authView = query.get("mode");
  const localPanel = reset ? <ResetPasswordForm token={reset}/> : authView === "register" ? <LocalRegistrationForm/> : authView === "forgot" ? <PasswordRecoveryForm/> : <LocalLoginForm/>;
  return <main className="relative grid min-h-screen overflow-hidden bg-[#071326] text-[#F5F7FB] lg:grid-cols-[1.03fr_.97fr]"><div className="pointer-events-none absolute -left-40 top-24 size-[600px] rounded-full bg-[#1B64F2]/20 blur-[130px]"/><section className="relative z-10 flex min-h-[500px] flex-col border-b border-white/10 p-6 sm:p-10 lg:min-h-screen lg:border-b-0 lg:border-r lg:border-white/10 lg:p-14"><div className="flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-1 text-sm font-bold text-[#A9BFDF] transition hover:text-white"><ChevronLeft size={17}/>Back to site</Link><BrandMark/></div><div className="mt-auto max-w-xl pt-24 lg:pt-0"><p className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.15em] text-[#8CB7FF]"><ShieldCheck size={14}/>Private operations access</p><h1 className="mt-4 font-display text-5xl font-bold leading-[.86] tracking-[-.08em] sm:text-7xl">The operational view, protected.</h1><p className="mt-6 max-w-lg text-base leading-7 text-[#A9BFDF]">Amarktai Network keeps sales context, review decisions, workload and audit evidence behind authenticated access and a second verification layer.</p><div className="mt-8 grid gap-3 text-sm font-semibold text-[#C8D8F2]"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#70A2FF]"/>Operational data remains access controlled.</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#70A2FF]"/>Action history stays connected to each decision.</span></div></div><div className="pointer-events-none absolute bottom-8 right-[-3rem] w-[37%] min-w-[230px] opacity-70"><img src={securityImage} alt="" className="w-full rounded-3xl"/></div></section><section className="relative z-10 grid place-items-center p-5 sm:p-10"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-[#0C1E3E]/95 p-7 shadow-[0_28px_70px_rgba(0,0,0,.38)] backdrop-blur sm:p-10">{invite ? <InviteAcceptForm token={invite}/> : <><div className="grid size-12 place-items-center rounded-2xl border border-[#4D82E7]/30 bg-[#123467] text-[#9ABEFF]"><LockKeyhole size={20}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.15em] text-[#8CB7FF]">Amarktai Network access</p><h2 className="mt-3 font-display text-5xl font-bold leading-[.9] tracking-[-.075em]">Open operations.</h2>{mode.isLoading ? <p className="mt-5 text-sm text-[#A9BFDF]">Loading sign-in…</p> : mode.data?.local ? localPanel : <ManagedSignIn/>}</>}</div></section></main>;
}

function InviteAcceptForm({ token }: { token: string }) {
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [pending, setPending] = useState(false);
  const [acceptedEmail, setAcceptedEmail] = useState<string | null>(null);
  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (password !== confirm) return toast.error("The passwords do not match.");
    setPending(true);
    try {
      const response = await fetch("/api/team-admin/accept-invite", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password }) });
      const body = await response.json().catch(() => ({})) as { ok?: boolean; email?: string; error?: string };
      if (!response.ok) throw new Error(body.error || "Invitation could not be accepted.");
      window.history.replaceState({}, "", "/auth");
      setAcceptedEmail(body.email ?? "");
      toast.success("Your Amarktai account is ready. Sign in to continue.");
    } catch (error) { toast.error(error instanceof Error ? error.message : "Invitation could not be accepted."); }
    finally { setPending(false); }
  }
  if (acceptedEmail !== null) return <><div className="grid size-12 place-items-center rounded-2xl bg-emerald-400/10 text-emerald-200"><CheckCircle2 size={21}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.15em] text-[#8CB7FF]">Invitation accepted</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.07em]">Your workspace is ready.</h2><LocalLoginForm initialEmail={acceptedEmail}/></>;
  return <><div className="grid size-12 place-items-center rounded-2xl border border-[#4D82E7]/30 bg-[#123467] text-[#9ABEFF]"><UserPlus size={20}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.15em] text-[#8CB7FF]">Team invitation</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.07em]">Create your password.</h2><p className="mt-4 text-sm leading-6 text-[#A9BFDF]">This setup link is short-lived and becomes unusable after your password is created.</p><form onSubmit={submit} className="mt-6 grid gap-4"><label className="text-sm font-bold text-[#DCE8FA]">Password<input type="password" autoComplete="new-password" required minLength={12} value={password} onChange={event => setPassword(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none focus:border-[#4E8BFF]"/></label><label className="text-sm font-bold text-[#DCE8FA]">Confirm password<input type="password" autoComplete="new-password" required minLength={12} value={confirm} onChange={event => setConfirm(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none focus:border-[#4E8BFF]"/></label><button type="submit" disabled={pending} className="mt-2 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white hover:bg-[#2B76FF]">{pending ? "Activating…" : "Activate account"}<ArrowRight size={17}/></button></form><Fineprint/></>;
}

function ManagedSignIn() { return <><p className="mt-5 text-sm leading-6 text-[#A9BFDF]">Continue to your protected organisation identity flow. Once signed in, you can open the command centre and controlled operations workspace.</p><button onClick={() => startLogin()} className="mt-8 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white shadow-[0_10px_25px_rgba(27,100,242,.28)] transition hover:-translate-y-0.5 hover:bg-[#2B76FF] active:scale-[.98]">Continue to operations <ArrowRight size={17}/></button><Fineprint/></>; }
function LocalRegistrationForm() { const [, navigate] = useLocation(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const register = trpc.auth.register.useMutation({ onSuccess: () => { toast.success("Workspace created. Complete email verification to enter operations."); navigate("/dashboard"); }, onError: error => toast.error(error.message) }); return <form onSubmit={event => { event.preventDefault(); register.mutate({ name, email, password }); }} className="mt-6 grid gap-4"><p className="text-sm leading-6 text-[#A9BFDF]">Create a private sales workspace. Email verification is required before operational access.</p><Field label="Name" value={name} onChange={setName} autoComplete="name"/><Field label="Email" value={email} onChange={setEmail} type="email" autoComplete="email"/><Field label="Password" value={password} onChange={setPassword} type="password" autoComplete="new-password"/><button disabled={register.isPending} className="mt-2 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white hover:bg-[#2B76FF]">{register.isPending ? "Creating…" : "Create workspace"}<ArrowRight size={17}/></button><button type="button" onClick={() => navigate("/auth")} className="text-sm font-bold text-[#9ABEFF] hover:text-white">Already have an account? Sign in</button><Fineprint/></form>; }
function PasswordRecoveryForm() { const [, navigate] = useLocation(); const [email, setEmail] = useState(""); const request = trpc.auth.requestPasswordReset.useMutation({ onSuccess: () => { toast.success("If that account is eligible, a recovery link has been sent."); navigate("/auth"); }, onError: () => { toast.success("If that account is eligible, a recovery link has been sent."); navigate("/auth"); } }); return <form onSubmit={event => { event.preventDefault(); request.mutate({ email }); }} className="mt-6 grid gap-4"><p className="text-sm leading-6 text-[#A9BFDF]">Enter your email. If an eligible account and SMTP delivery are configured, a short-lived recovery link will be sent.</p><Field label="Email" value={email} onChange={setEmail} type="email" autoComplete="email"/><button disabled={request.isPending} className="mt-2 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white hover:bg-[#2B76FF]">{request.isPending ? "Requesting…" : "Send recovery link"}<ArrowRight size={17}/></button><button type="button" onClick={() => navigate("/auth")} className="text-sm font-bold text-[#9ABEFF] hover:text-white">Back to sign in</button><Fineprint/></form>; }
function ResetPasswordForm({ token }: { token: string }) { const [, navigate] = useLocation(); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const reset = trpc.auth.resetPassword.useMutation({ onSuccess: () => { toast.success("Password reset. Complete email verification to enter operations."); navigate("/dashboard"); }, onError: error => toast.error(error.message) }); return <form onSubmit={event => { event.preventDefault(); if (password !== confirm) return toast.error("The passwords do not match."); reset.mutate({ token, password }); }} className="mt-6 grid gap-4"><p className="text-sm leading-6 text-[#A9BFDF]">Choose a new password. This recovery link expires after 30 minutes and becomes invalid once used.</p><Field label="New password" value={password} onChange={setPassword} type="password" autoComplete="new-password"/><Field label="Confirm password" value={confirm} onChange={setConfirm} type="password" autoComplete="new-password"/><button disabled={reset.isPending} className="mt-2 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white hover:bg-[#2B76FF]">{reset.isPending ? "Resetting…" : "Reset password"}<ArrowRight size={17}/></button><Fineprint/></form>; }
function LocalLoginForm({ initialEmail = "" }: { initialEmail?: string }) {
  const [, navigate] = useLocation();
  const [email, setEmail] = useState(initialEmail);
  const [password, setPassword] = useState("");
  const login = trpc.auth.localLogin.useMutation({ onSuccess: () => { toast.success("Signed in. Complete access verification to enter operations."); navigate("/dashboard"); }, onError: error => toast.error(error.message) });
  return <form onSubmit={event => { event.preventDefault(); login.mutate({ email, password }); }} className="mt-6 grid gap-4">
    <div><label htmlFor="email" className="text-sm font-bold text-[#DCE8FA]">Email</label><input id="email" type="email" autoComplete="email" required value={email} onChange={event => setEmail(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none transition placeholder:text-[#607EA8] focus:border-[#4E8BFF]"/></div>
    <div><label htmlFor="password" className="text-sm font-bold text-[#DCE8FA]">Password</label><input id="password" type="password" autoComplete="current-password" required minLength={12} value={password} onChange={event => setPassword(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none transition placeholder:text-[#607EA8] focus:border-[#4E8BFF]"/></div>
    <button type="submit" disabled={login.isPending} className="mt-3 inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#1B64F2] text-sm font-bold text-white shadow-[0_10px_25px_rgba(27,100,242,.28)] transition hover:-translate-y-0.5 hover:bg-[#2B76FF] active:scale-[.98]">{login.isPending ? "Signing in…" : "Enter operations"}<ArrowRight size={17}/></button>
    <div className="flex flex-wrap justify-center gap-x-4 gap-y-2 text-sm font-bold text-[#9ABEFF]"><button type="button" onClick={() => navigate("/auth?mode=forgot")} className="hover:text-white">Forgot password?</button><button type="button" onClick={() => navigate("/auth?mode=register")} className="hover:text-white">Create workspace</button></div>
    <Fineprint/>
  </form>;
}
function Field({ label, value, onChange, type = "text", autoComplete }: { label: string; value: string; onChange: (value: string) => void; type?: string; autoComplete?: string }) { return <label className="text-sm font-bold text-[#DCE8FA]">{label}<input type={type} autoComplete={autoComplete} required minLength={type === "password" ? 12 : undefined} value={value} onChange={event => onChange(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-white/15 bg-[#08182F] px-3 text-white outline-none focus:border-[#4E8BFF]"/></label>; }
function Fineprint() { return <p className="mt-7 text-center text-xs leading-5 text-[#7693BB]">Credentials and connection secrets remain on the server.</p>; }
