import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { Cable, CheckCircle2, CircleAlert, Link2, Loader2, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const capabilities = ["contacts.read", "companies.read", "opportunities.read", "tasks.read", "activities.read", "notes.read"];
const writableCapabilities = ["contacts.write", "opportunities.write", "tasks.write", "activities.write", "notes.write"];
type Provider = "genie" | "hubspot" | "salesforce" | "pipedrive" | "zoho" | "custom_browser" | "custom_api" | "csv_import";
type Method = "oauth" | "browser" | "sidecar" | "custom_adapter" | "import";

function defaultMethod(provider: Provider): Method { return provider === "hubspot" || provider === "salesforce" || provider === "pipedrive" ? "oauth" : provider === "custom_browser" || provider === "genie" ? "browser" : provider === "csv_import" ? "import" : "custom_adapter"; }
function statusLabel(status: string) { return status.replaceAll("_", " "); }
function statusClass(status: string) { return status === "ready" ? "bg-emerald-400/15 text-emerald-200" : status === "limited_permissions" ? "bg-amber-400/15 text-amber-100" : status === "needs_attention" || status === "authentication_expired" || status === "error" ? "bg-rose-400/15 text-rose-100" : "bg-white/8 text-[#A9BFDF]"; }

export default function Connections() {
  const organisation = trpc.organisation.current.useQuery();
  const organisationId = organisation.data?.organisationId;
  const systems = trpc.connectedSystems.list.useQuery({ organisationId: organisationId ?? 0 }, { enabled: Boolean(organisationId) });
  const [isAdding, setIsAdding] = useState(false);
  const [provider, setProvider] = useState<Provider>("hubspot");
  const [displayName, setDisplayName] = useState("HubSpot");
  const [baseUrl, setBaseUrl] = useState("");
  const method = useMemo(() => defaultMethod(provider), [provider]);
  const addDomain = trpc.connectedSystems.addDomain.useMutation();
  const create = trpc.connectedSystems.create.useMutation({
    onSuccess: async id => {
      if (organisationId && baseUrl.trim()) {
        try { await addDomain.mutateAsync({ organisationId, connectedSystemId: id, hostname: new URL(baseUrl).hostname, allowedPaths: ["/"] }); } catch (error) { toast.error(error instanceof Error ? error.message : "System saved but its authorised domain still needs approval."); }
      }
      await systems.refetch(); setIsAdding(false); toast.success("Connected system added. Authentication and backend testing are still required.");
    }, onError: error => toast.error(error.message),
  });
  const beginOAuth = trpc.connectedSystems.beginOAuth.useMutation({ onSuccess: result => window.location.assign(result.authorizationUrl), onError: error => toast.error(error.message) });
  const verify = trpc.connectedSystems.verify.useMutation({ onSuccess: async result => { await systems.refetch(); toast.success(result.status === "ready" ? "Connection verified." : result.summary); }, onError: error => toast.error(error.message) });
  const sync = trpc.connectedSystems.sync.useMutation({ onSuccess: async result => { await systems.refetch(); toast.success(`Sync complete: ${Object.values(result).reduce((total, value) => total + value, 0)} records processed.`); }, onError: error => toast.error(error.message) });

  const [sidecarToken, setSidecarToken] = useState("");
  const issueSidecar = trpc.sidecar.issueSession.useMutation({ onSuccess: result => { setSidecarToken(result.token); toast.success("A short-lived sidecar session was issued for this browser."); }, onError: error => toast.error(error.message) });
  const revokeSidecar = trpc.sidecar.revokeSessions.useMutation({ onSuccess: () => { setSidecarToken(""); toast.success("All browser-sidecar sessions for this account were revoked."); }, onError: error => toast.error(error.message) });

  function addSystem() {
    if (!organisationId) return;
    create.mutate({ organisationId, provider, displayName: displayName.trim() || provider, baseUrl: baseUrl.trim() || null, connectionMethod: method, allowedReadCapabilities: capabilities, allowedWriteCapabilities: writableCapabilities });
  }

  return <DashboardLayout><div className="mx-auto max-w-[1600px]">
    <header className="flex flex-col gap-6 border-b border-white/10 pb-7 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#83AEFF]">AMARKTAI / CONNECTED SYSTEMS</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.07em] text-white sm:text-5xl">Attach intelligence to the system your team already uses.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#A9BFDF] sm:text-base">Add one authorised company system at a time. The server, not this screen, verifies credentials and decides whether a connection is ready for work.</p></div><Button onClick={() => setIsAdding(value => !value)} className="h-11 rounded-xl bg-[#1B64F2] font-bold hover:bg-[#2B76FF]"><Plus className="mr-2 size-4"/>{isAdding ? "Close setup" : "Add system"}</Button></header>
    {isAdding && <section className="mt-6 rounded-[1.5rem] border border-[#3D69AD]/45 bg-[#0E2142] p-6 shadow-[0_18px_40px_rgba(0,0,0,.16)]"><div className="grid gap-5 xl:grid-cols-[1fr_1fr_1.1fr_auto]"><Field label="System"><select value={provider} onChange={event => { const value = event.target.value as Provider; setProvider(value); setDisplayName(value === "hubspot" ? "HubSpot" : value === "genie" ? "Genie" : value.replaceAll("_", " ")); }} className="h-11 w-full rounded-xl border border-white/15 bg-[#08172F] px-3 text-sm text-white outline-none"><option value="hubspot">HubSpot</option><option value="genie">Genie</option><option value="custom_browser">Custom browser CRM</option><option value="salesforce">Salesforce</option><option value="pipedrive">Pipedrive</option><option value="zoho">Zoho</option><option value="csv_import">Import / export</option></select></Field><Field label="Name your system"><Input value={displayName} onChange={event => setDisplayName(event.target.value)} className="border-white/15 bg-[#08172F] text-white"/></Field><Field label="Company CRM URL (required for browser systems)"><Input value={baseUrl} onChange={event => setBaseUrl(event.target.value)} placeholder="https://crm.company.example" className="border-white/15 bg-[#08172F] text-white placeholder:text-[#607EA8]"/></Field><div className="flex items-end"><Button disabled={create.isPending || !displayName.trim() || ((provider === "genie" || provider === "custom_browser") && !baseUrl.trim())} onClick={addSystem} className="h-11 w-full bg-[#1B64F2] hover:bg-[#2B76FF]">{create.isPending ? <Loader2 className="size-4 animate-spin"/> : "Save system"}</Button></div></div><p className="mt-4 text-xs leading-5 text-[#9DB3D5]">Connection method: <strong className="font-bold text-[#C6D8F8]">{method.replaceAll("_", " ")}</strong>. Amarktai requests only the supplied read/write capabilities and limits browser sidecar activation to the registered company domain.</p></section>}
    <section className="mt-7 grid gap-4 2xl:grid-cols-2">{systems.data?.length ? systems.data.map(system => <article key={system.id} className="rounded-[1.5rem] border border-white/10 bg-[#0E2142] p-6 shadow-[0_18px_40px_rgba(0,0,0,.16)]"><div className="flex items-start justify-between gap-4"><div className="flex min-w-0 gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#153B7A] text-[#9FC2FF]"><Cable size={19}/></span><div><h2 className="truncate font-display text-2xl font-bold tracking-[-.05em] text-white">{system.displayName}</h2><p className="mt-1 text-xs text-[#91A9CF]">{system.provider.replaceAll("_", " ")} · {system.connectionMethod.replaceAll("_", " ")}{system.baseUrl ? ` · ${system.baseUrl}` : ""}</p></div></div><span className={cn("inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[.11em]", statusClass(system.status))}>{system.status === "ready" && <CheckCircle2 size={12}/>} {statusLabel(system.status)}</span></div><div className="mt-5 grid gap-3 border-y border-white/10 py-4 text-sm sm:grid-cols-3"><Metric label="Verified" value={system.verifiedCapabilities.length ? system.verifiedCapabilities.length : "Not tested"}/><Metric label="Last check" value={system.lastHealthCheckAt ? new Date(system.lastHealthCheckAt).toLocaleString() : "Never"}/><Metric label="Access" value={`${system.allowedReadCapabilities.length} read · ${system.allowedWriteCapabilities.length} write`}/></div>{system.lastHealthSummary && <p className="mt-4 rounded-xl bg-black/15 p-3 text-xs leading-5 text-[#B5C8E7]">{system.lastHealthSummary}</p>}<div className="mt-5 flex flex-wrap gap-2">{system.connectionMethod === "oauth" && <Button size="sm" disabled={beginOAuth.isPending} onClick={() => organisationId && beginOAuth.mutate({ organisationId, connectedSystemId: system.id })} className="bg-[#1B64F2] hover:bg-[#2B76FF]"><Link2 className="mr-2 size-4"/>Connect</Button>}<Button size="sm" variant="outline" disabled={verify.isPending} onClick={() => organisationId && verify.mutate({ organisationId, connectedSystemId: system.id })} className="border-white/15 bg-white/5 text-white hover:bg-white/10"><ShieldCheck className="mr-2 size-4"/>Test connection</Button>{(system.status === "ready" || system.status === "limited_permissions") && <Button size="sm" variant="outline" disabled={sync.isPending} onClick={() => organisationId && sync.mutate({ organisationId, connectedSystemId: system.id })} className="border-white/15 bg-white/5 text-white hover:bg-white/10"><RefreshCw className="mr-2 size-4"/>Sync</Button>}</div></article>) : <EmptySystems/>}</section>
    <section className="mt-6 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-[1.5rem] border border-white/10 bg-[#0E2142] p-6"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#153B7A] text-[#9FC2FF]"><ShieldCheck size={18}/></span><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#7FAAF8]">AUTHORISED-DOMAIN CONTROL</p><h2 className="font-display text-2xl font-bold tracking-[-.05em] text-white">The sidecar does not watch the web.</h2></div></div><p className="mt-4 max-w-3xl text-sm leading-6 text-[#A9BFDF]">Amarktai’s browser sidecar is intended only for the approved company domains registered with a connected system. It does not monitor personal browsing, unrelated websites, keystrokes, webcams, or microphones.</p></article><article className="rounded-[1.5rem] border border-amber-300/15 bg-amber-400/[.05] p-6"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-amber-400/15 text-amber-100"><CircleAlert size={18}/></span><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-amber-100">CONNECTION HEALTH</p><h2 className="font-display text-2xl font-bold tracking-[-.05em] text-white">Fix attention items promptly.</h2></div></div><p className="mt-4 text-sm leading-6 text-[#E0D1AD]">A disconnected, expired, or limited connection is displayed explicitly. No CRM action is called successful until its connector confirms it.</p></article></section>
    <section className="mt-6 rounded-[1.5rem] border border-white/10 bg-[#0E2142] p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#7FAAF8]">BROWSER SIDECAR</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-.05em] text-white">Connect a side panel for this browser.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#A9BFDF]">Issue an eight-hour session only when you are ready to pair the Amarktai Sidecar extension. It can retrieve context only for the active, authorised company domain.</p></div><div className="flex flex-wrap gap-2"><Button disabled={!organisationId || issueSidecar.isPending} onClick={() => organisationId && issueSidecar.mutate({ organisationId })} className="bg-[#1B64F2] hover:bg-[#2B76FF]">Issue sidecar session</Button><Button variant="outline" disabled={!organisationId || revokeSidecar.isPending} onClick={() => organisationId && revokeSidecar.mutate({ organisationId })} className="border-white/15 bg-white/5 text-white hover:bg-white/10">Revoke sessions</Button></div></div>{sidecarToken && <div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-400/[.07] p-4"><p className="text-xs font-bold text-amber-100">Copy this once into the Sidecar extension. It expires in eight hours and is not stored in Amarktai as plaintext.</p><div className="mt-3 flex gap-2"><Input readOnly value={sidecarToken} className="border-white/15 bg-[#08172F] font-mono text-xs text-white"/><Button variant="outline" onClick={() => navigator.clipboard.writeText(sidecarToken).then(() => toast.success("Sidecar session copied."))} className="border-white/15 bg-white/5 text-white hover:bg-white/10">Copy</Button></div></div>}</section>
  </div></DashboardLayout>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2"><span className="text-[10px] font-black uppercase tracking-[.13em] text-[#8CA9D4]">{label}</span>{children}</label>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#7896C1]">{label}</p><p className="mt-1 truncate font-semibold text-[#E4ECFA]">{value}</p></div>; }
function EmptySystems() { return <article className="col-span-full rounded-[1.5rem] border border-dashed border-white/15 bg-white/[.03] p-10 text-center"><Cable className="mx-auto size-8 text-[#7FAAF8]"/><h2 className="mt-4 font-display text-3xl font-bold tracking-[-.05em] text-white">No connected systems yet.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[#9DB3D5]">Start with HubSpot or Genie. A system remains disconnected until its authentication and backend capability checks have been completed.</p></article>; }
