import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { Activity, ArrowRight, CalendarClock, CheckCircle2, Clock3, Download, Headphones, Network, ShieldCheck, Workflow } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";

export default function Dashboard() {
  const [, navigate] = useLocation();
  const query = trpc.assistant.operationsDashboard.useQuery();
  const exportData = trpc.assistant.exportWorkspaceData.useMutation({
    onSuccess: file => {
      const binary = atob(file.base64);
      const bytes = Uint8Array.from(binary, character => character.charCodeAt(0));
      const url = URL.createObjectURL(new Blob([bytes], { type: file.contentType }));
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = file.filename;
      anchor.click();
      URL.revokeObjectURL(url);
      toast.success(`${file.filename} is ready.`);
    },
    onError: error => toast.error(`Export failed: ${error.message}`),
  });
  const data = query.data;
  if (query.isLoading) return <DashboardLayout><Loading/></DashboardLayout>;
  if (query.isError) return <DashboardLayout><ApiError detail={query.error.message} retry={() => query.refetch()}/></DashboardLayout>;
  if (!data) return <DashboardLayout><Empty title="No operations data is available." text="The dashboard will populate with real workspace activity as workflows, callbacks, call sessions, proposals, and connection profiles are created."/></DashboardLayout>;
  return <DashboardLayout><div className="mx-auto max-w-[1600px]"><header className="flex flex-col gap-5 border-b border-white/10 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#83AEFF]">AMARKTAI NETWORK / OPERATIONS DASHBOARD</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.07em] text-white sm:text-5xl">Run the sales day with a clear view.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#A9BFDF] sm:text-base">This is a live view of the data stored in the workspace. Empty panels are accurate: they indicate that no matching activity has yet been recorded.</p></div><div className="flex flex-wrap gap-2"><Button disabled={exportData.isPending} onClick={() => exportData.mutate({ kind: "operational_report", format: "csv" })} variant="outline" className="h-11 rounded-xl border-white/15 bg-white/5 px-4 text-[#DCE8FA] hover:bg-white/10 hover:text-white"><Download className="mr-2 size-4"/>{exportData.isPending ? "Preparing export…" : "Report CSV"}</Button><Button disabled={exportData.isPending} onClick={() => exportData.mutate({ kind: "conversation_log", format: "pdf" })} variant="outline" className="h-11 rounded-xl border-white/15 bg-white/5 px-4 text-[#DCE8FA] hover:bg-white/10 hover:text-white"><Download className="mr-2 size-4"/>{exportData.isPending ? "Preparing export…" : "Call logs PDF"}</Button><Button onClick={() => navigate("/workflows")} className="h-11 rounded-xl bg-[#1B64F2] px-4 font-bold hover:bg-[#2B76FF]"><Workflow className="mr-2 size-4"/>Prepare workflow</Button><Button onClick={() => navigate("/calls")} variant="outline" className="h-11 rounded-xl border-white/15 bg-white/5 px-4 text-[#DCE8FA] hover:bg-white/10 hover:text-white"><Headphones className="mr-2 size-4"/>Start call session</Button></div></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={ShieldCheck} label="Needs review" value={data.metrics.reviewRequired} detail="External work waiting for a decision"/><Metric icon={Clock3} label="Open callbacks" value={data.metrics.openCallbacks} detail={`${data.metrics.dueTodayCallbacks} due today · ${data.metrics.overdueCallbacks} overdue`} alert={data.metrics.overdueCallbacks > 0}/><Metric icon={Headphones} label="Live calls" value={data.metrics.activeCalls} detail={`${data.metrics.callsReadyForReview} ready for review`}/><Metric icon={CheckCircle2} label="Executed actions" value={data.metrics.executedActions} detail={`${data.metrics.blockedActions} blocked with a recorded reason`} alert={data.metrics.blockedActions > 0}/><Metric icon={Workflow} label="Prepared workflows" value={data.metrics.preparedWorkflows} detail="Current governed work in progress"/></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Panel><Heading icon={ShieldCheck} eyebrow="DECISIONS REQUIRED" title="Review queue"/><div className="mt-5 space-y-3">{data.queues.reviewProposals.length ? data.queues.reviewProposals.map(item => <article key={item.id} className="rounded-xl border border-white/10 bg-[#0B1B37] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-bold text-white">{item.title}</p><p className="mt-1 text-sm text-[#A9BFDF]">{item.targetLabel} · {item.actionType.replaceAll("_", " ")}</p></div><button onClick={() => navigate("/workspace")} className="inline-flex shrink-0 items-center gap-1 text-sm font-bold text-[#83AEFF]">Open review <ArrowRight size={15}/></button></div></article>) : <Empty title="No decisions are waiting." text="Prepared external actions will appear here before they can run."/>}</div></Panel><Panel><Heading icon={CalendarClock} eyebrow="WORKLOAD" title="Callback focus"/><Queue label="Overdue" items={data.queues.overdueCallbacks} empty="No overdue callbacks." alert/><Queue label="Due today" items={data.queues.dueTodayCallbacks} empty="Nothing is due today."/></Panel></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Panel><Heading icon={Headphones} eyebrow="CONVERSATIONS" title="Call work"/><Queue label="Live now" items={data.queues.activeCalls} empty="No live sessions are in progress."/><Queue label="Ready for review" items={data.queues.callsReadyForReview} empty="No call summaries are waiting."/><button onClick={() => navigate("/calls")} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#83AEFF]">Open call desk <ArrowRight size={15}/></button></Panel><Panel><Heading icon={Activity} eyebrow="AGENT ACTIVITY" title="Retained operational events"/><div className="mt-5 space-y-2">{data.recent.agentActivity.length ? data.recent.agentActivity.map(event => <ActivityCard key={event.id} summary={event.summary} label={event.eventType} date={event.createdAt}/>) : <Empty title="No retained activity yet." text="Workflow preparation, call coaching and guarded action attempts will create activity records here."/>}</div></Panel></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[.95fr_1.05fr]"><Panel><Heading icon={Network} eyebrow="LIVE READINESS" title="Service checks"/><div className="mt-5 grid gap-2 sm:grid-cols-2"><Readiness label="CRM browser bridge" ready={data.connectionReadiness.crmBrowserBridge}/><Readiness label="Messaging and calendar link" ready={data.connectionReadiness.microsoftConnection}/><Readiness label="Amarktai intelligence service" ready={data.connectionReadiness.intelligenceService}/><Readiness label="Email delivery" ready={data.connectionReadiness.emailDelivery}/></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#82AAEE]">Saved connection profiles</p><div className="mt-3 space-y-2">{data.recent.connections.length ? data.recent.connections.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-[#0B1B37] p-3"><div><p className="font-bold capitalize text-white">{item.provider}</p><p className="mt-1 text-xs text-[#9DB3D5]">{item.displayName}</p></div><Status text={item.status}/></div>) : <p className="text-sm text-[#8FA9CE]">No connection profiles are saved yet.</p>}</div></div><button onClick={() => navigate("/connections")} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#83AEFF]">Open connection settings <ArrowRight size={15}/></button></Panel><Panel><Heading icon={Activity} eyebrow="AUDIT ACTIVITY" title="The recent decision trail"/><div className="mt-5 space-y-2">{data.recent.audit.length ? data.recent.audit.map(event => <ActivityCard key={event.id} summary={event.summary} label={event.eventType} date={event.createdAt}/>) : <Empty title="No audit records yet." text="A retained activity trail starts when operational work begins."/>}</div></Panel></section>
  </div></DashboardLayout>;
}

function Panel({ children }: { children: React.ReactNode }) { return <section className="rounded-[1.5rem] border border-white/10 bg-[#0E2142] p-5 shadow-[0_18px_40px_rgba(0,0,0,.16)] sm:p-6">{children}</section>; }
function Heading({ icon: Icon, eyebrow, title }: { icon: typeof ShieldCheck; eyebrow: string; title: string }) { return <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#153B7A] text-[#94B9FF]"><Icon size={18}/></span><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#7FAAF8]">{eyebrow}</p><h2 className="font-display text-2xl font-bold tracking-[-.05em] text-white">{title}</h2></div></div>; }
function Metric({ icon: Icon, label, value, detail, alert = false }: { icon: typeof ShieldCheck; label: string; value: number; detail: string; alert?: boolean }) { return <Panel><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-[#A9BFDF]">{label}</p><p className="mt-2 font-display text-4xl font-bold tracking-[-.07em] text-white">{value}</p></div><span className={cn("grid size-10 place-items-center rounded-xl", alert ? "bg-amber-400/15 text-amber-200" : "bg-[#153B7A] text-[#94B9FF]")}><Icon size={18}/></span></div><p className="mt-3 text-xs leading-5 text-[#849FC5]">{detail}</p></Panel>; }
function Queue({ label, items, empty, alert = false }: { label: string; items: Array<{ id: number; leadLabel: string; title?: string; status?: string; dueAt?: Date | null }>; empty: string; alert?: boolean }) { return <div className="mt-5"><p className={cn("text-[10px] font-black uppercase tracking-[.14em]", alert ? "text-amber-200" : "text-[#82AAEE]")}>{label}</p><div className="mt-2 space-y-2">{items.length ? items.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-[#0B1B37] px-3 py-2.5"><div><p className="text-sm font-bold text-white">{item.leadLabel}</p><p className="mt-0.5 text-xs text-[#92ABCF]">{item.title || item.status?.replaceAll("_", " ") || "Workspace item"}</p></div>{item.dueAt && <p className="text-xs font-semibold text-[#9EB6DB]">{new Date(item.dueAt).toLocaleDateString()}</p>}</div>) : <p className="rounded-xl bg-white/[.04] px-3 py-3 text-sm text-[#8EA8CF]">{empty}</p>}</div></div>; }
function ActivityCard({ summary, label, date }: { summary: string; label: string; date: Date }) { return <article className="rounded-xl border border-white/10 bg-[#0B1B37] p-3"><p className="text-sm font-semibold text-[#E4ECFA]">{summary}</p><p className="mt-1 text-xs text-[#829CC2]">{label.replaceAll("_", " ")} · {new Date(date).toLocaleString()}</p></article>; }
function Readiness({ label, ready }: { label: string; ready: boolean }) { return <div className="flex items-center justify-between rounded-xl border border-white/10 bg-[#0B1B37] px-3 py-3"><p className="text-sm font-semibold text-[#DCE8FA]">{label}</p><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[.12em]", ready ? "bg-emerald-400/15 text-emerald-200" : "bg-white/8 text-[#9EB6DB]")}>{ready ? "Configured" : "Not configured"}</span></div>; }
function Status({ text }: { text: string }) { return <span className="rounded-full bg-[#153B7A] px-2.5 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#94B9FF]">{text.replaceAll("_", " ")}</span>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-dashed border-white/15 bg-white/[.03] p-5 text-center"><p className="font-bold text-[#E4ECFA]">{title}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#8FA9CE]">{text}</p></div>; }
function Loading() { return <div className="mx-auto grid max-w-[1600px] gap-4 md:grid-cols-3"><div className="h-32 animate-pulse rounded-2xl bg-white/5"/><div className="h-32 animate-pulse rounded-2xl bg-white/5"/><div className="h-32 animate-pulse rounded-2xl bg-white/5"/></div>; }
function ApiError({ detail, retry }: { detail: string; retry: () => void }) { return <div className="mx-auto max-w-2xl rounded-[1.5rem] border border-rose-300/20 bg-rose-400/10 p-6 text-[#FCE8EC]"><p className="font-display text-2xl font-bold">The operations dashboard could not load.</p><p className="mt-3 text-sm leading-6 text-rose-100/90">{detail || "The workspace request failed. Check your connection or selected organisation, then retry."}</p><Button onClick={retry} className="mt-5 bg-[#1B64F2] hover:bg-[#2B76FF]">Retry dashboard request</Button></div>; }
