import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Building2, CheckCircle2, Globe2, Network, Plus, Rocket, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const capabilities = ["contacts", "tasks", "opportunities", "notes", "activities", "email", "calendar"] as const;
type Capability = (typeof capabilities)[number];
type CrmForm = { provider: "genie" | "hubspot" | "salesforce" | "pipedrive" | "zoho" | "custom_browser" | "custom_api"; displayName: string; connectionMethod: "oauth" | "browser" | "custom_adapter"; capabilities: Capability[] };

const steps = ["Company profile", "Website discovery", "Knowledge review", "CRM connection", "Playbooks", "Go-live review"];
function Card({ children }: { children: React.ReactNode }) { return <section className="rounded-[1.75rem] border border-white/10 bg-[#0C1E3E] p-6 sm:p-8">{children}</section>; }
function StepHeading({ icon: Icon, number, title, text }: { icon: typeof Building2; number: string; title: string; text: string }) { return <div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#153B7A] text-[#9FC2FF]"><Icon size={18}/></span><div><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#83AEFF]">Step {number}</p><h2 className="mt-1 font-display text-2xl font-bold text-white">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#A9BFDF]">{text}</p></div></div>; }

export default function Onboarding() {
  const utils = trpc.useUtils();
  const organisation = trpc.organisation.current.useQuery();
  const organisationId = organisation.data?.organisationId;
  const setup = trpc.companySetup.get.useQuery();
  const systems = trpc.connectedSystems.list.useQuery({ organisationId: organisationId ?? 0 }, { enabled: Boolean(organisationId) });
  const [step, setStep] = useState(1);
  const [profile, setProfile] = useState({ companyName: "", websiteUrl: "", industry: "", companySize: "", primaryMarket: "", salesMotion: "", brandVoice: "" });
  const [preview, setPreview] = useState<{ sourceUrl: string; proposedKnowledge: Array<{ title: string; content: string }> } | null>(null);
  const [selectedKnowledge, setSelectedKnowledge] = useState<number[]>([]);
  const [crm, setCrm] = useState<CrmForm>({ provider: "custom_browser", displayName: "", connectionMethod: "browser", capabilities: ["contacts", "tasks", "notes", "activities"] });
  const [playbook, setPlaybook] = useState({ title: "", trigger: "", description: "", agentKey: "supervisor" });

  useEffect(() => { const saved = setup.data?.profile; if (saved) setProfile({ companyName: saved.companyName, websiteUrl: saved.websiteUrl ?? "", industry: saved.industry ?? "", companySize: saved.companySize ?? "", primaryMarket: saved.primaryMarket ?? "", salesMotion: saved.salesMotion ?? "", brandVoice: saved.brandVoice ?? "" }); }, [setup.data?.profile]);
  const saveProfile = trpc.companySetup.saveProfile.useMutation({ onSuccess: () => { utils.companySetup.get.invalidate(); setStep(2); toast.success("Company profile saved."); }, onError: error => toast.error(error.message) });
  const discover = trpc.companySetup.discoverWebsite.useMutation({ onSuccess: result => { setPreview(result); setSelectedKnowledge(result.proposedKnowledge.map((_, index) => index)); setStep(3); toast.success("Website context is ready for review. Nothing has been stored."); }, onError: error => toast.error(error.message) });
  const confirm = trpc.companySetup.confirmDiscovery.useMutation({ onSuccess: () => { utils.companySetup.get.invalidate(); setPreview(null); setStep(4); toast.success("Selected knowledge was confirmed."); }, onError: error => toast.error(error.message) });
  const addConnection = trpc.connectedSystems.create.useMutation({ onSuccess: () => { systems.refetch(); setStep(5); toast.success("Connection registered. Configure and verify it before use."); }, onError: error => toast.error(error.message) });
  const savePlaybook = trpc.companySetup.savePlaybook.useMutation({ onSuccess: () => { utils.companySetup.get.invalidate(); setStep(6); toast.success("Review-first playbook saved."); }, onError: error => toast.error(error.message) });
  const profileSaved = Boolean(setup.data?.profile); const knowledgeConfirmed = setup.data?.profile?.discoveryStatus === "confirmed"; const readySystems = systems.data?.filter(system => system.status === "ready") ?? [];

  return <DashboardLayout><div className="mx-auto max-w-5xl space-y-6 text-[#EEF5FF]"><Card><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#83AEFF]">Organisation intelligence</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.06em] text-white sm:text-5xl">Set up your <span className="text-[#83AEFF]">Sales Assistant.</span></h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[#B7CAE7]">Build a trusted organisation context. Connections are server-verified, knowledge is explicitly confirmed, and external actions remain review-first.</p></Card><nav className="grid gap-2 rounded-[1.5rem] border border-white/10 bg-[#0C1E3E] p-3 sm:grid-cols-6">{steps.map((label, index) => <button key={label} onClick={() => setStep(index + 1)} className={`rounded-xl px-3 py-3 text-left text-xs font-bold ${step === index + 1 ? "bg-[#153B7A] text-white" : "text-[#A9BFDF] hover:bg-white/[.05]"}`}><span className="mr-2 text-[#83AEFF]">{String(index + 1).padStart(2, "0")}</span>{label}</button>)}</nav>
    {step === 1 && <Card><StepHeading icon={Building2} number="01" title="Tell us about your organisation" text="This private profile supplies the approved operating context for the selected workspace."/><div className="mt-6 grid gap-4 sm:grid-cols-2"><Input value={profile.companyName} onChange={event => setProfile({ ...profile, companyName: event.target.value })} placeholder="Your organisation" className="border-white/15 bg-[#08172F] text-white"/><Input value={profile.websiteUrl} onChange={event => setProfile({ ...profile, websiteUrl: event.target.value })} placeholder="https://example.com" className="border-white/15 bg-[#08172F] text-white"/><Input value={profile.industry} onChange={event => setProfile({ ...profile, industry: event.target.value })} placeholder="Industry" className="border-white/15 bg-[#08172F] text-white"/><Input value={profile.primaryMarket} onChange={event => setProfile({ ...profile, primaryMarket: event.target.value })} placeholder="Primary market" className="border-white/15 bg-[#08172F] text-white"/></div><Textarea value={profile.brandVoice} onChange={event => setProfile({ ...profile, brandVoice: event.target.value })} placeholder="Approved voice, policies, and sales guidance…" className="mt-4 min-h-28 border-white/15 bg-[#08172F] text-white"/><Button disabled={!profile.companyName || saveProfile.isPending} onClick={() => saveProfile.mutate(profile)} className="mt-5 bg-[#1B64F2]">Save and continue</Button></Card>}
    {step === 2 && <Card><StepHeading icon={Globe2} number="02" title="Preview website context" text="A safe preview blocks private and non-HTML destinations. Unconfirmed content is not retained."/><Button disabled={!profileSaved || discover.isPending} onClick={() => discover.mutate()} className="mt-6 bg-[#1B64F2]">Start secure preview</Button></Card>}
    {step === 3 && <Card><StepHeading icon={BadgeCheck} number="03" title="Confirm usable knowledge" text="Only selected public website facts become approved workspace knowledge."/>{preview ? <><div className="mt-6 space-y-3">{preview.proposedKnowledge.map((item, index) => <label key={`${item.title}-${index}`} className="flex gap-3 rounded-xl border border-white/10 bg-[#08172F] p-4"><input type="checkbox" checked={selectedKnowledge.includes(index)} onChange={() => setSelectedKnowledge(selectedKnowledge.includes(index) ? selectedKnowledge.filter(value => value !== index) : [...selectedKnowledge, index])}/><span><b>{item.title}</b><span className="mt-1 block text-sm text-[#A9BFDF]">{item.content}</span></span></label>)}</div><Button disabled={confirm.isPending} onClick={() => confirm.mutate({ knowledgeIndexes: selectedKnowledge })} className="mt-5 bg-[#1B64F2]">Confirm selected knowledge</Button></> : <p className="mt-5 text-sm text-[#A9BFDF]">Start a fresh website preview first.</p>}</Card>}
    {step === 4 && <Card><StepHeading icon={Network} number="04" title="Connect and verify a CRM" text="Register a connection, then configure and verify it. Only server verification marks it usable."/><div className="mt-6 grid gap-4 sm:grid-cols-2"><select value={crm.provider} onChange={event => { const provider = event.target.value as CrmForm["provider"]; setCrm({ ...crm, provider, connectionMethod: provider === "custom_browser" || provider === "genie" ? "browser" : provider === "custom_api" ? "custom_adapter" : "oauth" }); }} className="h-11 rounded-xl border border-white/15 bg-[#08172F] px-3 text-white"><option value="hubspot">HubSpot</option><option value="salesforce">Salesforce</option><option value="pipedrive">Pipedrive</option><option value="zoho">Zoho</option><option value="genie">CRM workspace bridge</option><option value="custom_browser">Custom browser CRM</option><option value="custom_api">Custom API adapter</option></select><Input value={crm.displayName} onChange={event => setCrm({ ...crm, displayName: event.target.value })} placeholder="Connection display name" className="border-white/15 bg-[#08172F] text-white"/></div><div className="mt-4 flex flex-wrap gap-2">{capabilities.map(capability => <button key={capability} onClick={() => setCrm({ ...crm, capabilities: crm.capabilities.includes(capability) ? crm.capabilities.filter(item => item !== capability) : [...crm.capabilities, capability] })} className={`rounded-full border px-3 py-1 text-xs ${crm.capabilities.includes(capability) ? "border-[#4E8BFF] bg-[#153B7A]" : "border-white/10"}`}>{capability}</button>)}</div><Button disabled={!organisationId || !crm.displayName || !crm.capabilities.length || addConnection.isPending} onClick={() => organisationId && addConnection.mutate({ organisationId, provider: crm.provider, displayName: crm.displayName, connectionMethod: crm.connectionMethod, allowedReadCapabilities: crm.capabilities, allowedWriteCapabilities: crm.capabilities })} className="mt-5 bg-[#1B64F2]"><Plus className="mr-2 size-4"/>Register connection</Button></Card>}
    {step === 5 && <Card><StepHeading icon={ShieldCheck} number="05" title="Create a review-first playbook" text="Playbooks prepare controlled work. They never authorise external actions."/><Input value={playbook.title} onChange={event => setPlaybook({ ...playbook, title: event.target.value })} placeholder="Playbook title" className="mt-6 border-white/15 bg-[#08172F] text-white"/><Input value={playbook.trigger} onChange={event => setPlaybook({ ...playbook, trigger: event.target.value })} placeholder="Trigger" className="mt-4 border-white/15 bg-[#08172F] text-white"/><Textarea value={playbook.description} onChange={event => setPlaybook({ ...playbook, description: event.target.value })} placeholder="What should the assistant prepare?" className="mt-4 min-h-28 border-white/15 bg-[#08172F] text-white"/><Button disabled={!playbook.title || !playbook.trigger || !playbook.description || savePlaybook.isPending} onClick={() => savePlaybook.mutate({ ...playbook, requiredCapabilities: ["tasks"], status: "draft" })} className="mt-5 bg-[#1B64F2]">Save playbook</Button></Card>}
    {step === 6 && <Card><StepHeading icon={Rocket} number="06" title="Review go-live readiness" text="This review reports stored server evidence; it does not claim live provider proof."/><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["Profile", profileSaved], ["Knowledge", knowledgeConfirmed], ["Verified CRM", readySystems.length > 0]].map(([label, ready]) => <div key={String(label)} className="rounded-xl border border-white/10 bg-[#08172F] p-4"><p className="font-bold text-white">{label}</p><p className={`mt-2 text-sm ${ready ? "text-emerald-200" : "text-amber-200"}`}>{ready ? "Recorded" : "Still required"}</p></div>)}</div><p className="mt-5 text-sm leading-6 text-[#A9BFDF]">Before deployment, configure installation secrets, run migrations, verify the connector with authorised credentials, and complete the documented SMTP and health checks.</p></Card>}
  </div></DashboardLayout>;
}
