import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { AlertTriangle, BarChart3, CircleAlert, RefreshCw, Users } from "lucide-react";

function money(valueMinor: number) { try { return new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(valueMinor / 100); } catch { return `${valueMinor / 100}`; } }

export default function TeamIntelligence() {
  const organisation = trpc.organisation.current.useQuery();
  const organisationId = organisation.data?.organisationId;
  const query = trpc.management.teamIntelligence.useQuery({ organisationId: organisationId ?? 0 }, { enabled: Boolean(organisationId) });
  if (query.isLoading || organisation.isLoading) return <DashboardLayout><div className="grid min-h-[60vh] place-items-center text-[#A9BFDF]">Loading Team Intelligence…</div></DashboardLayout>;
  if (query.error) return <DashboardLayout><div className="mx-auto max-w-3xl rounded-2xl border border-amber-300/20 bg-amber-400/[.07] p-6 text-amber-100">{query.error.message}</div></DashboardLayout>;
  const data = query.data;
  return <DashboardLayout><div className="mx-auto max-w-[1600px]"><header className="flex flex-col gap-5 border-b border-white/10 pb-7 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#83AEFF]">AMARKTAI / TEAM INTELLIGENCE</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.07em] text-white sm:text-5xl">See where management attention is needed.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#A9BFDF] sm:text-base">These exceptions are calculated from synchronized CRM tasks, opportunities, and owner mapping. They are not inferred from private browsing or a continuous AI conversation.</p></div><Button variant="outline" onClick={() => query.refetch()} className="border-white/15 bg-white/5 text-white hover:bg-white/10"><RefreshCw className="mr-2 size-4"/>Refresh</Button></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={Users} label="Mapped salespeople" value={data?.summary.mappedSalespeople ?? 0} detail="CRM owners linked to members"/><Metric icon={AlertTriangle} label="Need attention" value={data?.summary.needsAttention ?? 0} detail="People with actionable exceptions" alert/><Metric icon={CircleAlert} label="Overdue tasks" value={data?.summary.overdueTasks ?? 0} detail="Open tasks past their due date" alert/><Metric icon={BarChart3} label="Stale opportunities" value={data?.summary.staleOpportunities ?? 0} detail="No recent CRM activity" alert/><Metric icon={BarChart3} label="Pipeline at risk" value={money(data?.summary.pipelineAtRiskMinor ?? 0)} detail="Value on stale opportunities" alert/></section>
    <section className="mt-6 rounded-[1.5rem] border border-white/10 bg-[#0E2142] p-5 shadow-[0_18px_40px_rgba(0,0,0,.16)] sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#153B7A] text-[#9FC2FF]"><Users size={18}/></span><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#7FAAF8]">EXCEPTION QUEUE</p><h2 className="font-display text-2xl font-bold tracking-[-.05em] text-white">Start with the people who need help.</h2></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[780px] text-left"><thead className="border-b border-white/10 text-[10px] font-black uppercase tracking-[.12em] text-[#7896C1]"><tr><th className="pb-3 pr-4">Salesperson</th><th className="pb-3 pr-4 text-right">Overdue tasks</th><th className="pb-3 pr-4 text-right">Stale opportunities</th><th className="pb-3 pr-4 text-right">No next step</th><th className="pb-3 pr-4 text-right">Pipeline at risk</th><th className="pb-3 text-right">Attention score</th></tr></thead><tbody>{data?.people.length ? data.people.map(person => <tr key={person.externalUserId} className={cn("border-b border-white/[.07]", person.exceptionScore ? "bg-amber-400/[.025]" : "")}><td className="py-4 pr-4"><p className="font-bold text-white">{person.name}</p><p className="mt-1 text-xs text-[#8FA9CE]">{person.userId ? "Mapped Amarktai member" : "CRM owner not yet linked"}</p></td><td className="py-4 pr-4 text-right font-semibold text-[#E4ECFA]">{person.overdueTasks}</td><td className="py-4 pr-4 text-right font-semibold text-[#E4ECFA]">{person.staleOpportunities}</td><td className="py-4 pr-4 text-right font-semibold text-[#E4ECFA]">{person.noNextStep}</td><td className="py-4 pr-4 text-right font-semibold text-[#D4E4FF]">{money(person.pipelineAtRiskMinor)}</td><td className="py-4 text-right"><span className={cn("rounded-full px-2.5 py-1 text-xs font-black", person.exceptionScore ? "bg-amber-400/15 text-amber-100" : "bg-emerald-400/15 text-emerald-200")}>{person.exceptionScore}</span></td></tr>) : <tr><td colSpan={6} className="py-12 text-center text-sm text-[#9DB3D5]">No external CRM owner mappings are available. Synchronize a system and map its owners to Amarktai members before relying on team metrics.</td></tr>}</tbody></table></div></section>
  </div></DashboardLayout>;
}
function Metric({ icon: Icon, label, value, detail, alert = false }: { icon: typeof Users; label: string; value: string | number; detail: string; alert?: boolean }) { return <article className="rounded-2xl border border-white/10 bg-[#0E2142] p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-[#A9BFDF]">{label}</p><p className="mt-2 font-display text-3xl font-bold tracking-[-.065em] text-white">{value}</p></div><span className={cn("grid size-10 place-items-center rounded-xl", alert ? "bg-amber-400/15 text-amber-100" : "bg-[#153B7A] text-[#9FC2FF]")}><Icon size={18}/></span></div><p className="mt-3 text-xs leading-5 text-[#849FC5]">{detail}</p></article>; }
