import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { Activity, ArrowRight, BarChart3, Bot, Cable, CheckCircle2, Clock3, FileText, Headphones, LibraryBig, LockKeyhole, MessageSquareText, Play, Plus, Send, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const workflows = [
  { key: "first_contact", name: "First contact sequence", copy: "Template-bound outreach and the governed Call 2 progression." },
  { key: "cyber_post_consultation", name: "Cyber post-consultation", copy: "A factual, outcome-dependent follow-up workflow." },
  { key: "cyber_final_close", name: "Cyber final close", copy: "A current-record-only final closure process." },
] as const;
type WorkflowKey = (typeof workflows)[number]["key"];
type Result = Record<string, unknown> | null | undefined;

function Frame({ children }: { children: React.ReactNode }) { return <DashboardLayout>{children}</DashboardLayout>; }
function Panel({ children, className }: { children: React.ReactNode; className?: string }) { return <section className={cn("rounded-[1.5rem] border border-[#DDE9F9] bg-white shadow-[0_12px_32px_rgba(25,81,166,.05)]", className)}>{children}</section>; }
function Header({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: React.ReactNode }) { return <div className="flex flex-col gap-5 border-b border-[#E0EAF8] pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#1463F3]">{eyebrow}</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.07em] text-[#08255C] sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#607DA5] sm:text-base">{description}</p></div>{children}</div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-[#C8DBF5] bg-[#F8FBFF] p-7 text-center"><p className="font-bold text-[#08255C]">{title}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#6A86AC]">{text}</p></div>; }
function Pill({ children, tone = "blue" }: { children: React.ReactNode; tone?: "blue" | "amber" | "green" | "red" }) { const tones = { blue: "bg-blue-50 text-[#1463F3]", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700", red: "bg-rose-50 text-rose-700" }; return <span className={cn("rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-[.12em]", tones[tone])}>{children}</span>; }

function Supervisor() {
  const [command, setCommand] = useState("");
  const route = trpc.assistant.routeCommand.useMutation({ onError: error => toast.error(error.message) });
  return <Panel className="mt-6 overflow-hidden bg-[linear-gradient(100deg,#F3F8FF,white)] p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end"><div className="max-w-2xl"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#1463F3]">SUPERVISOR AGENT</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-.06em] text-[#08255C]">Start with the instruction, not the interface.</h2><p className="mt-2 text-sm leading-6 text-[#607DA5]">Describe the work in plain language. The Supervisor identifies the safe route, required facts, and whether a governed workflow is needed.</p></div><div className="flex w-full gap-2 lg:max-w-xl"><Input value={command} onChange={event => setCommand(event.target.value)} onKeyDown={event => event.key === "Enter" && command.trim().length > 3 && route.mutate({ command })} placeholder="Prepare the final Cyber close for Amara Daniels" className="h-11 rounded-xl border-[#C9DCF7] bg-white"/><Button onClick={() => route.mutate({ command })} disabled={route.isPending || command.trim().length < 4} className="h-11 rounded-xl bg-[#1463F3] hover:bg-[#0A4FD2]">{route.isPending ? "Routing…" : "Route"}</Button></div></div>{route.data && <div className="mt-5 rounded-xl border border-[#DCE8F9] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-[#08255C]">{route.data.summary}</p><p className="mt-1 text-sm text-[#6380A8]">Required: {route.data.requiredInputs.length ? route.data.requiredInputs.join(" · ") : "No additional input for this view."}</p></div><Pill>{route.data.intent}</Pill></div><p className="mt-3 text-xs leading-5 text-[#6A86AC]">Control: {route.data.guardrails[0]}</p></div>}</Panel>;
}

export function CommandCentre() {
  const [, navigate] = useLocation();
  const dashboard = trpc.assistant.dashboard.useQuery();
  const analytics = trpc.analytics.summary.useQuery();
  const audit = trpc.analytics.audit.useQuery({ limit: 5 });
  const review = trpc.assistant.reviewAction.useMutation({ onSuccess: () => { dashboard.refetch(); analytics.refetch(); audit.refetch(); toast.success("Proposal updated."); }, onError: error => toast.error(error.message) });
  const execute = trpc.assistant.executeApprovedGenieAction.useMutation({ onSuccess: () => { dashboard.refetch(); analytics.refetch(); audit.refetch(); toast.success("Action executed and evidence recorded."); }, onError: error => { dashboard.refetch(); analytics.refetch(); audit.refetch(); toast.error(error.message); } });
  const summary = analytics.data;
  return <Frame><Header eyebrow="AMARKTAI AI / COMMAND CENTRE" title="Every sales day, in sharper focus." description="A live view of governed work, agent activity, evidence and the next operational decision."><Button onClick={() => navigate("/workflows")} className="rounded-xl bg-[#1463F3] font-bold hover:bg-[#0A4FD2]"><Workflow className="mr-2 size-4"/>Prepare workflow</Button></Header><div className="mt-8 grid gap-4 md:grid-cols-3"><Metric icon={ShieldCheck} label="Awaiting review" value={summary?.reviewRequired ?? 0} copy="Actions held for a human decision"/><Metric icon={Activity} label="Executed actions" value={summary?.executed ?? 0} copy="Confirmed outcomes with retained results"/><Metric icon={Clock3} label="Open callbacks" value={summary?.openCallbacks ?? 0} copy="Planned activity still to complete"/></div><Supervisor/><div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Panel className="p-5 sm:p-6"><Section title="Review queue" eyebrow="CONTROLLED EXECUTION" icon={ShieldCheck}/><div className="mt-5 space-y-3">{dashboard.isLoading ? <Empty title="Loading protected work" text="Your owned action proposals are being retrieved."/> : dashboard.data?.proposals.length ? dashboard.data.proposals.map(proposal => <ProposalCard key={proposal.id} proposal={proposal} onReview={(state) => review.mutate({ proposalId: proposal.id, state })} onExecute={() => execute.mutate({ proposalId: proposal.id })} executing={execute.isPending}/>) : <Empty title="Your review queue is clear." text="Prepare a governed workflow to create a controlled proposal."/>}</div></Panel><Panel className="p-6"><Section title="Recent audit evidence" eyebrow="OPERATIONAL HISTORY" icon={FileText}/><div className="mt-5 space-y-3">{audit.data?.length ? audit.data.map(entry => <article key={entry.id} className="rounded-xl bg-[#F6F9FF] p-3"><p className="text-sm font-bold text-[#08255C]">{entry.summary}</p><p className="mt-1 text-xs text-[#718DB3]">{entry.eventType.replaceAll("_", " ")} · {new Date(entry.createdAt).toLocaleString()}</p></article>) : <Empty title="No audit records yet." text="Operational decisions and execution evidence will appear here."/>}</div></Panel></div></Frame>;
}

function ProposalCard({ proposal, onReview, onExecute, executing }: { proposal: { id: number; title: string; targetLabel: string; actionType: string; state: string; executionResult: Result }; onReview: (state: "approved" | "skipped") => void; onExecute: () => void; executing: boolean }) {
  const result = proposal.executionResult;
  const screenshot = result && typeof result.screenshotUrl === "string" ? result.screenshotUrl : result && typeof result.screenshotPath === "string" ? result.screenshotPath : null;
  const tone = proposal.state === "executed" ? "green" : proposal.state === "blocked" ? "red" : proposal.state === "review_required" ? "amber" : "blue";
  return <article className="rounded-2xl border border-[#E0EAF9] p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#EAF2FF] text-[#1463F3]"><Send size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold text-[#08255C]">{proposal.title}</p><p className="mt-1 text-sm text-[#6B87AD]">{proposal.targetLabel} · {proposal.actionType.replaceAll("_", " ")}</p></div><Pill tone={tone}>{proposal.state.replaceAll("_", " ")}</Pill></div>{result && <div className="mt-3 rounded-xl border border-[#DDE9F9] bg-[#F8FBFF] p-3"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#6685AF]">Execution result</p><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap break-words text-xs leading-5 text-[#46658E]">{JSON.stringify(result, null, 2)}</pre>{screenshot && <a href={screenshot} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-[#1463F3]">Open captured evidence <ArrowRight size={13}/></a>}{!screenshot && <p className="mt-2 text-xs leading-5 text-[#6683AA]">Evidence status: no screenshot captured. Calibrate a `screenshot` step in the saved Genie script before the next approved run.</p>}</div>}<ProposalAudit proposalId={proposal.id}/>{proposal.state === "blocked" && <p className="mt-3 rounded-xl bg-rose-50 p-3 text-xs leading-5 text-rose-700">This action was blocked. Review the structured result, correct the configured CRM script, selector, permission or prerequisite, and prepare a new proposal only when the condition is resolved.</p>}</div><div className="flex shrink-0 flex-wrap gap-2">{proposal.state === "review_required" && <><Button size="sm" variant="outline" onClick={() => onReview("skipped")}>Skip</Button><Button size="sm" className="bg-[#1463F3] hover:bg-[#0A4FD2]" onClick={() => onReview("approved")}>Approve</Button></>}{proposal.state === "approved" && <Button size="sm" disabled={executing} className="bg-[#0A2C69] hover:bg-[#08255C]" onClick={onExecute}>{executing ? "Running…" : "Run action"}</Button>}</div></div></article>;
}

function ProposalAudit({ proposalId }: { proposalId: number }) {
  const audit = trpc.assistant.proposalAudit.useQuery({ proposalId });
  if (!audit.data?.length) return null;
  return <div className="mt-3 border-t border-[#E1EAF8] pt-3"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#6E8CB3]">Proposal audit trail</p><div className="mt-2 space-y-2">{audit.data.map(event => <article key={event.id} className="rounded-lg bg-[#F7FAFF] p-2.5"><p className="text-xs leading-5 text-[#58769E]"><span className="font-bold text-[#264F8E]">{new Date(event.createdAt).toLocaleString()}</span> · {event.summary}</p>{Object.keys(event.metadata).length > 0 && <dl className="mt-2 grid gap-1 text-[11px] leading-4 text-[#6B86AB]">{Object.entries(event.metadata).filter(([key]) => ["script", "completedAt", "detail", "evidence", "screenshotPath", "success"].includes(key)).map(([key, value]) => <div key={key} className="grid grid-cols-[105px_1fr] gap-2"><dt className="font-bold text-[#46658E]">{key}</dt><dd className="break-words">{typeof value === "string" ? value : JSON.stringify(value)}</dd></div>)}</dl>}</article>)}</div></div>;
}

export function WorkflowStudio() {
  const [, navigate] = useLocation(); const [workflowKey, setWorkflowKey] = useState<WorkflowKey>("first_contact"); const [leadLabel, setLeadLabel] = useState(""); const [callOutcome, setCallOutcome] = useState<"no_answer" | "voicemail" | "answered">("no_answer"); const [notes, setNotes] = useState("");
  const prepare = trpc.assistant.prepareWorkflow.useMutation({ onSuccess: () => { toast.success("Review-ready workflow prepared."); navigate("/workspace"); }, onError: error => toast.error(error.message) }); const postConsultation = workflowKey === "cyber_post_consultation";
  return <Frame><Header eyebrow="AMARKTAI AI / WORKFLOW STUDIO" title="Turn a playbook into a controlled plan." description="Select an approved path, give the factual context, and let the system prepare—not perform—the next actions."/><div className="mt-8 grid gap-6 xl:grid-cols-[.78fr_1.22fr]"><section className="rounded-[1.5rem] bg-[#0A2C69] p-7 text-white"><p className="text-[10px] font-black uppercase tracking-[.16em] text-blue-200">WHY GOVERNANCE MATTERS</p><h2 className="mt-4 font-display text-4xl font-bold tracking-[-.065em]">Confidence without the leap of faith.</h2><div className="mt-8 space-y-4 text-sm leading-6 text-blue-100/75"><p>Every workflow starts by reviewing current tasks, history and opportunities.</p><p>Approved templates, senders and duplicate boundaries are retained with the proposal.</p><p>A human sees every external write before it runs.</p></div></section><Panel className="p-6"><div className="grid gap-5">{workflows.map(flow => <button key={flow.key} onClick={() => setWorkflowKey(flow.key)} className={cn("rounded-xl border p-4 text-left", workflowKey === flow.key ? "border-[#1463F3] bg-[#F2F7FF]" : "border-[#E0EAF9]")}><p className="font-bold text-[#08255C]">{flow.name}</p><p className="mt-1 text-sm text-[#6784AA]">{flow.copy}</p></button>)}<Field label="Candidate or contact"><Input value={leadLabel} onChange={event => setLeadLabel(event.target.value)} placeholder="Amara Daniels"/></Field>{postConsultation && <><Field label="Call outcome"><div className="grid grid-cols-3 gap-2">{(["no_answer", "voicemail", "answered"] as const).map(value => <Button key={value} variant="outline" onClick={() => setCallOutcome(value)} className={cn("capitalize", callOutcome === value && "border-[#1463F3] bg-[#EAF2FF] text-[#1463F3]")}>{value.replace("_", " ")}</Button>)}</div></Field><Field label="Factual call notes"><Textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Only what was said, asked, agreed or objected to…"/></Field></>}<Button disabled={prepare.isPending || !leadLabel.trim()} onClick={() => prepare.mutate({ workflowKey, leadLabel, ...(postConsultation ? { callOutcome, conversationNotes: notes || undefined } : {}) })} className="h-12 bg-[#1463F3] hover:bg-[#0A4FD2]">Prepare review-ready workflow <ArrowRight className="ml-2 size-4"/></Button></div></Panel></div></Frame>;
}

export function CallDesk() {
  const [leadLabel, setLeadLabel] = useState(""); const [transcript, setTranscript] = useState(""); const [sessionId, setSessionId] = useState<number | null>(null); const [tip, setTip] = useState(""); const [summary, setSummary] = useState("");
  const start = trpc.calls.startLive.useMutation({ onSuccess: id => { setSessionId(id); toast.success("Live coaching session started."); }, onError: error => toast.error(error.message) });
  const coach = trpc.calls.coachTranscript.useMutation({ onSuccess: result => setTip(result.content), onError: error => toast.error(error.message) });
  const complete = trpc.calls.completeLive.useMutation({ onSuccess: result => { setSummary(result.content); toast.success("Call summary saved for review."); }, onError: error => toast.error(error.message) });
  return <Frame><Header eyebrow="AMARKTAI AI / LIVE CALL DESK" title="Keep the rep human. Make the context sharper." description="Start a protected session, paste verified notes or transcript, then request a factual coaching tip or post-call summary."/><div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Panel className="p-6"><Section title="Live call session" eyebrow="FACTUAL COACHING" icon={Headphones}/><div className="mt-6 grid gap-4"><Field label="Candidate or contact"><Input value={leadLabel} onChange={event => setLeadLabel(event.target.value)} placeholder="Amara Daniels"/></Field><Field label="Live transcript or factual notes"><Textarea value={transcript} onChange={event => setTranscript(event.target.value)} className="min-h-52" placeholder="Paste only the words, questions, objections and agreements you actually heard…"/></Field><div className="flex flex-wrap gap-2">{!sessionId ? <Button disabled={!leadLabel.trim() || start.isPending} onClick={() => start.mutate({ leadLabel })} className="bg-[#1463F3] hover:bg-[#0A4FD2]"><Play className="mr-2 size-4"/>Start coaching session</Button> : <><Button disabled={!transcript.trim() || coach.isPending} onClick={() => coach.mutate({ callSessionId: sessionId, leadLabel, transcriptChunk: transcript })} className="bg-[#1463F3] hover:bg-[#0A4FD2]">Request coaching tip</Button><Button variant="outline" disabled={!transcript.trim() || complete.isPending} onClick={() => complete.mutate({ callSessionId: sessionId, leadLabel, transcript })}>Complete & summarise</Button></>}</div></div></Panel><section className="rounded-[1.5rem] bg-[#EAF2FF] p-7"><Section title="Conversation Coach" eyebrow="REVIEWABLE GUIDANCE" icon={MessageSquareText}/>{tip ? <ResultBlock title="Live coaching tip" content={tip}/> : <p className="mt-6 text-sm leading-7 text-[#5D7AA3]">The coach will summarize what it heard, suggest a safe question or response, and identify the next step. It asks for clarification rather than filling gaps with imagined candidate facts.</p>}{summary && <ResultBlock title="Post-call summary" content={summary}/>}</section></div></Frame>;
}

export function AgentDesk() { const agents = trpc.assistant.agents.useQuery(); const [selected, setSelected] = useState("conversation_coach"); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const chat = trpc.assistant.chat.useMutation({ onSuccess: result => setAnswer(result.content), onError: error => toast.error(error.message) }); return <Frame><Header eyebrow="AMARKTAI AI / AGENT DESK" title="Use a specialist with boundaries." description="Every agent has a defined job. Programme answers are grounded in approved knowledge; communications and CRM actions remain proposals."/><div className="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]"><Panel className="p-3">{agents.data?.agents.map(agent => <button key={agent.key} onClick={() => setSelected(agent.key)} className={cn("mb-1 w-full rounded-xl p-4 text-left", selected === agent.key ? "bg-[#0A2C69] text-white" : "hover:bg-[#F4F8FF]")}><p className={cn("font-bold", selected === agent.key ? "text-white" : "text-[#08255C]")}>{agent.name}</p><p className={cn("mt-1 text-xs", selected === agent.key ? "text-blue-100/65" : "text-[#718DB2]")}>{agent.modelRole}</p></button>)}</Panel><Panel className="p-6"><Field label="Ask the selected specialist"><Textarea value={question} onChange={event => setQuestion(event.target.value)} className="min-h-40" placeholder="Ask for coaching, context or approved programme guidance…"/></Field><Button disabled={!question.trim() || chat.isPending} onClick={() => chat.mutate({ agentKey: selected, messages: [{ role: "user", content: question }] })} className="mt-4 bg-[#1463F3] hover:bg-[#0A4FD2]">Ask specialist <ArrowRight className="ml-2 size-4"/></Button>{answer && <ResultBlock title="Review-ready guidance" content={answer}/>}</Panel></div></Frame>; }

export function KnowledgeHub() { const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const sources = trpc.knowledge.list.useQuery(); const add = trpc.knowledge.add.useMutation({ onSuccess: () => { setTitle(""); setContent(""); sources.refetch(); toast.success("Approved knowledge source added."); }, onError: error => toast.error(error.message) }); return <Frame><Header eyebrow="AMARKTAI AI / KNOWLEDGE" title="Make accurate answers easier." description="Approved programme and policy sources are retrieved for the Knowledge Agent before it explains a Course2Career offering."/><div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel className="p-6"><Section title="Add approved context" eyebrow="KNOWLEDGE CONTROL" icon={LibraryBig}/><div className="mt-6 grid gap-4"><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Cyber Security programme FAQ"/><Textarea value={content} onChange={event => setContent(event.target.value)} className="min-h-52" placeholder="Paste approved policy or programme content…"/><Button disabled={!title.trim() || !content.trim() || add.isPending} onClick={() => add.mutate({ title, content, sourceType: "note" })} className="bg-[#1463F3] hover:bg-[#0A4FD2]">Add approved source</Button></div></Panel><Panel className="p-6"><Section title="Available to agents" eyebrow="RETRIEVAL CONTEXT" icon={CheckCircle2}/><div className="mt-6 space-y-3">{sources.data?.length ? sources.data.map(source => <article key={source.id} className="rounded-xl border border-[#E0EAF9] p-4"><p className="font-bold text-[#08255C]">{source.title}</p><p className="mt-1 text-sm text-[#708BB0]">{source.sourceType} · {source.status}</p></article>) : <Empty title="No sources yet." text="Add verified programme information before asking the Knowledge Agent to explain it."/>}</div></Panel></div></Frame>; }

export function ConnectionsPage() { const list = trpc.integrations.list.useQuery(); const outlook = trpc.outlook.readiness.useQuery(); const profile = trpc.integrations.createProfile.useMutation({ onSuccess: () => { list.refetch(); toast.success("Connection profile saved."); }, onError: error => toast.error(error.message) }); const cards = [{ provider: "genie" as const, name: "Genie CRM", ready: list.data?.genie.configured, copy: "Browser bridge, reviewed saved scripts, execution evidence and no API key." }, { provider: "outlook" as const, name: "Outlook", ready: outlook.data?.ready, copy: "Graph application readiness and validated saved-template email inputs." }, { provider: "genx" as const, name: "GenX AI", ready: list.data?.genx.ready, copy: "Model routing for specialist agents, coaching and structured summaries." }]; return <Frame><Header eyebrow="AMARKTAI AI / CONNECTIONS" title="Connect the stack. Keep the control." description="Credentials are server-side. Connections expose only readiness, their operational purpose, and a protected route to reviewed action proposals."/><div className="mt-8 grid gap-5 xl:grid-cols-3">{cards.map(card => <Panel key={card.provider} className="flex flex-col p-6"><span className="grid size-12 place-items-center rounded-2xl bg-[#EAF2FF] text-[#1463F3]"><Cable size={20}/></span><div className="mt-6 flex items-center justify-between gap-3"><h2 className="font-display text-3xl font-bold tracking-[-.055em] text-[#08255C]">{card.name}</h2><Pill tone={card.ready ? "green" : "blue"}>{card.ready ? "Ready" : "Needs setup"}</Pill></div><p className="mt-4 text-sm leading-6 text-[#6683AA]">{card.copy}</p><Button variant="outline" disabled={profile.isPending} onClick={() => profile.mutate({ provider: card.provider, displayName: `${card.name} production profile`, scopeSummary: card.copy })} className="mt-6 border-[#CDE0FF] text-[#1463F3] hover:bg-[#F3F8FF]"><Plus className="mr-2 size-4"/>Save profile</Button></Panel>)}</div></Frame>; }

function Metric({ icon: Icon, label, value, copy }: { icon: typeof ShieldCheck; label: string; value: number; copy: string }) { return <Panel className="p-5"><div className="flex justify-between"><div><p className="text-sm font-semibold text-[#6C88AE]">{label}</p><p className="mt-2 font-display text-4xl font-bold tracking-[-.07em] text-[#08255C]">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-[#EAF2FF] text-[#1463F3]"><Icon size={18}/></span></div><p className="mt-3 text-xs text-[#8099BA]">{copy}</p></Panel>; }
function Section({ title, eyebrow, icon: Icon }: { title: string; eyebrow: string; icon: typeof ShieldCheck }) { return <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#EAF2FF] text-[#1463F3]"><Icon size={18}/></span><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#7591B8]">{eyebrow}</p><h2 className="font-display text-2xl font-bold tracking-[-.05em] text-[#08255C]">{title}</h2></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="text-sm font-bold text-[#08255C]">{label}</label><div className="mt-2">{children}</div></div>; }
function ResultBlock({ title, content }: { title: string; content: string }) { return <div className="mt-6 rounded-xl border border-[#CFE0FA] bg-white p-4"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#1463F3]">{title}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#47668E]">{content}</p></div>; }
