import { AIChatBox, type Message } from "@/components/AIChatBox";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { AlertTriangle, ArrowRight, Bot, Cable, CheckCircle2, ChevronRight, CircleDot, Clock3, FileText, Headphones, LibraryBig, MessageSquareText, Plus, Send, ShieldCheck, Sparkles, Workflow, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const workflowOptions = [
  { value: "first_contact", label: "First contact sequence", description: "Prepare the approved first-contact message and a guarded Call 2 proposal." },
  { value: "cyber_post_consultation", label: "Cyber post-consultation follow-up", description: "Handle Yes/No Cyber outcomes without inventing an outcome or duplicating outreach." },
  { value: "cyber_final_close", label: "Cyber Security final close", description: "Prepare the protected Lost close-out sequence for the current open record only." },
] as const;

const actionTone: Record<string, string> = {
  review_required: "bg-amber-50 text-amber-700 ring-amber-200",
  approved: "bg-sky-50 text-sky-700 ring-sky-200",
  skipped: "bg-slate-100 text-slate-600 ring-slate-200",
  executed: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  blocked: "bg-rose-50 text-rose-700 ring-rose-200",
};

function AppFrame({ children }: { children: React.ReactNode }) { return <DashboardLayout>{children}</DashboardLayout>; }

export function CommandCentre() {
  const [, navigate] = useLocation();
  const dashboard = trpc.assistant.dashboard.useQuery();
  const agents = trpc.assistant.agents.useQuery();
  const review = trpc.assistant.reviewAction.useMutation({ onSuccess: () => { dashboard.refetch(); toast.success("Proposal updated."); }, onError: error => toast.error(error.message) });
  const execute = trpc.assistant.executeApprovedGenieAction.useMutation({ onSuccess: () => { dashboard.refetch(); toast.success("Approved Genie script completed and evidence was recorded."); }, onError: error => { dashboard.refetch(); toast.error(error.message); } });
  const data = dashboard.data;

  return <AppFrame>
    <PageHeading eyebrow="Command centre" title="A safer kind of momentum." description="Prepare the work, check the context, then review every external action before anything leaves your control." action={<Button onClick={() => navigate("/workflows")} className="rounded-xl bg-[#102238] font-bold text-white hover:bg-[#19334f]"><Workflow className="mr-2 size-4" />Prepare a workflow</Button>} />
    <div className="mt-7 grid gap-4 sm:grid-cols-3">
      <Metric label="Awaiting review" value={data?.metrics.actionsAwaitingReview ?? 0} detail="External actions held safely" icon={ShieldCheck} tone="lime" />
      <Metric label="Open callbacks" value={data?.metrics.openCallbackTasks ?? 0} detail="Tracked in this workspace" icon={Clock3} tone="sky" />
      <Metric label="Knowledge sources" value={data?.metrics.knowledgeSources ?? 0} detail="Ready for programme guidance" icon={LibraryBig} tone="coral" />
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
      <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6">
        <SectionTitle icon={ShieldCheck} eyebrow="Review queue" title="Nothing runs ahead of you." />
        <div className="mt-5 space-y-3">
          {dashboard.isLoading ? <EmptyLine label="Loading protected proposals…" /> : data?.proposals.length ? data.proposals.map(proposal => <article key={proposal.id} className="flex flex-col gap-3 rounded-2xl border border-slate-200 p-4 lg:flex-row lg:items-center">
            <div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#eef6d1] text-[#5f7900]"><Send size={16} /></div>
            <div className="min-w-0 flex-1"><p className="font-bold text-[#102238]">{proposal.title}</p><p className="mt-1 text-sm text-slate-500">{proposal.targetLabel} · {proposal.actionType.replaceAll("_", " ")}</p></div>
            <div className="flex flex-wrap items-center justify-end gap-2"><span className={cn("rounded-full px-2.5 py-1 text-[11px] font-black uppercase tracking-wide ring-1", actionTone[proposal.state])}>{proposal.state.replaceAll("_", " ")}</span>{proposal.state === "review_required" && <><Button variant="outline" size="sm" className="rounded-lg" onClick={() => review.mutate({ proposalId: proposal.id, state: "skipped" })}>Skip</Button><Button size="sm" className="rounded-lg bg-[#102238]" onClick={() => review.mutate({ proposalId: proposal.id, state: "approved" })}>Approve</Button></>}{proposal.state === "approved" && <Button size="sm" disabled={execute.isPending} className="rounded-lg bg-[#6b8500] hover:bg-[#576e00]" onClick={() => execute.mutate({ proposalId: proposal.id })}>{execute.isPending ? "Running…" : "Run reviewed action"}</Button>}{proposal.executionResult && <p title={JSON.stringify(proposal.executionResult)} className="w-full text-right text-[11px] font-medium text-slate-500">{proposal.state === "executed" ? "Result and evidence recorded" : "Execution blocked — open audit details"}</p>}</div>
          </article>) : <EmptyState icon={ShieldCheck} title="Your review queue is clear." text="Create a workflow when you are ready. Every proposed CRM or communication action will land here first." />}
        </div>
      </section>
      <section className="rounded-[1.5rem] bg-[#102238] p-5 text-white shadow-[0_14px_34px_rgba(16,34,56,.18)] sm:p-6">
        <SectionTitle dark icon={Bot} eyebrow="Agent system" title="Specialists, not a black box." />
        <div className="mt-5 space-y-3">{agents.data?.agents.map(agent => <div key={agent.key} className="flex gap-3 rounded-xl border border-white/10 bg-white/[.055] p-3"><div className="mt-0.5 size-2 shrink-0 rounded-full bg-[#d8ff3e]" /><div><p className="text-sm font-bold">{agent.name}</p><p className="mt-1 text-xs leading-5 text-white/54">{agent.purpose}</p></div></div>)}</div>
        <button onClick={() => navigate("/agents")} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#d8ff3e]">Open the agent desk <ArrowRight size={15} /></button>
      </section>
    </div>
    <section className="mt-6 rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle icon={FileText} eyebrow="Recent preparation" title="An auditable activity trail." /><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data?.runs.length ? data.runs.map(run => <article key={run.id} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-slate-400">{run.workflowKey.replaceAll("_", " ")}</p><p className="mt-2 font-bold text-[#102238]">{run.leadLabel}</p><p className="mt-2 line-clamp-2 text-sm leading-5 text-slate-500">{run.verificationSummary}</p></article>) : <EmptyState icon={FileText} title="No workflow runs yet." text="Once you prepare a workflow, its reasoning and action proposals will appear here." />}</div></section>
  </AppFrame>;
}

export function WorkflowStudio() {
  const [workflowKey, setWorkflowKey] = useState<(typeof workflowOptions)[number]["value"]>("first_contact");
  const [leadLabel, setLeadLabel] = useState("");
  const [outcome, setOutcome] = useState<"no_answer" | "voicemail" | "answered">("no_answer");
  const [notes, setNotes] = useState("");
  const [, navigate] = useLocation();
  const prepare = trpc.assistant.prepareWorkflow.useMutation({ onSuccess: result => { toast.success(`${result.actionCount} reviewable action${result.actionCount === 1 ? "" : "s"} prepared.`); setLeadLabel(""); setNotes(""); navigate("/workspace"); }, onError: error => toast.error(error.message) });
  const current = workflowOptions.find(item => item.value === workflowKey)!;
  const requiresOutcome = workflowKey === "cyber_post_consultation";

  return <AppFrame>
    <PageHeading eyebrow="Workflow studio" title="Turn policy into a careful plan." description="Choose an approved Course2Career workflow, add only verified contact information, then send a review-first plan to your queue." />
    <div className="mt-7 grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
      <section className="rounded-[1.5rem] bg-[#102238] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.14em] text-[#d8ff3e]">Built-in guardrails</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.06em]">The system plans. Your team decides.</h2><div className="mt-7 space-y-4">{["Review the task, conversation, and opportunity context before a change.", "Use saved messages and the mandated SMS number instead of rewriting approved templates.", "Block duplicate tasks, messages, sequences, and historical-record changes."].map((copy, index) => <div key={copy} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-[#d8ff3e] text-xs font-black text-[#102238]">0{index + 1}</span><p className="text-sm leading-6 text-white/70">{copy}</p></div>)}</div></section>
      <section className="rounded-[1.5rem] border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="grid gap-5"><div><label className="text-sm font-bold text-[#102238]">Select a governed workflow</label><div className="mt-2 grid gap-2">{workflowOptions.map(option => <button key={option.value} onClick={() => setWorkflowKey(option.value)} className={cn("rounded-xl border p-4 text-left transition", workflowKey === option.value ? "border-[#102238] bg-[#f5f8fb] shadow-[3px_4px_0_#d8ff3e]" : "border-slate-200 hover:border-slate-300")}><p className="font-bold text-[#102238]">{option.label}</p><p className="mt-1 text-sm leading-5 text-slate-500">{option.description}</p></button>)}</div></div><div><label htmlFor="lead" className="text-sm font-bold text-[#102238]">Candidate or contact</label><Input id="lead" value={leadLabel} onChange={event => setLeadLabel(event.target.value)} placeholder="e.g. Amara Daniels" className="mt-2 h-11 rounded-xl border-slate-300" /></div>{requiresOutcome && <><div><label className="text-sm font-bold text-[#102238]">Follow-up result</label><div className="mt-2 grid grid-cols-3 gap-2">{(["no_answer", "voicemail", "answered"] as const).map(value => <button key={value} onClick={() => setOutcome(value)} className={cn("rounded-xl border px-3 py-2.5 text-sm font-bold capitalize", outcome === value ? "border-[#102238] bg-[#eef6d1] text-[#102238]" : "border-slate-200 text-slate-500")}>{value.replace("_", " ")}</button>)}</div></div><div><label htmlFor="notes" className="text-sm font-bold text-[#102238]">Factual call notes {outcome === "answered" ? "(required)" : "(optional)"}</label><Textarea id="notes" value={notes} onChange={event => setNotes(event.target.value)} placeholder={outcome === "answered" ? "Record only what the candidate said, agreed, asked, or objected to…" : "Optional context for the record…"} className="mt-2 min-h-28 rounded-xl border-slate-300" /></div></>}<div className="rounded-xl bg-[#f5f8fb] p-4 text-sm leading-6 text-slate-600"><strong className="text-[#102238]">What happens next:</strong> the assistant stores a protected plan and creates reviewable proposals. It will not contact a CRM, Outlook, email, SMS, or WhatsApp service directly from this screen.</div><Button disabled={prepare.isPending || !leadLabel.trim()} onClick={() => prepare.mutate({ workflowKey, leadLabel, ...(requiresOutcome ? { callOutcome: outcome, conversationNotes: notes || undefined } : {}) })} className="h-12 rounded-xl bg-[#102238] font-bold text-white hover:bg-[#19334f]">{prepare.isPending ? "Preparing protected plan…" : `Prepare ${current.label}`}<ArrowRight className="ml-2 size-4" /></Button></div></section>
    </div>
  </AppFrame>;
}

export function AgentDesk() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [agentKey, setAgentKey] = useState("conversation_coach");
  const catalog = trpc.assistant.agents.useQuery();
  const chat = trpc.assistant.chat.useMutation({ onSuccess: result => setMessages(previous => [...previous, { role: "assistant", content: result.content }]), onError: error => toast.error(error.message) });
  const agent = catalog.data?.agents.find(item => item.key === agentKey);
  const prompts = useMemo(() => ["Help me prepare for a candidate’s Cyber Security follow-up.", "Turn these factual call notes into a concise review summary.", "What Course2Career knowledge should I check before answering this question?"], []);

  function send(content: string) { const next = [...messages, { role: "user" as const, content }]; setMessages(next); chat.mutate({ agentKey, messages: next.map(message => ({ role: message.role === "system" ? "user" : message.role, content: message.content })) }); }
  return <AppFrame><PageHeading eyebrow="Agent desk" title="Ask a specialist, keep the control." description="Choose a role-specific agent. Messages are guidance and planning only; no external action is taken from chat." /><div className="mt-7 grid gap-6 lg:grid-cols-[300px_1fr]"><section className="rounded-[1.5rem] border border-slate-200 bg-white p-3 shadow-sm">{catalog.data?.agents.map(item => <button key={item.key} onClick={() => setAgentKey(item.key)} className={cn("mb-1 w-full rounded-xl p-4 text-left", agentKey === item.key ? "bg-[#102238] text-white" : "hover:bg-[#f5f8fb]")}><p className="font-bold">{item.name}</p><p className={cn("mt-1 text-xs leading-5", agentKey === item.key ? "text-white/60" : "text-slate-500")}>{item.modelRole}</p></button>)}</section><section className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><p className="font-bold text-[#102238]">{agent?.name || "Agent"}</p><p className="mt-1 text-sm text-slate-500">{agent?.purpose}</p></div><AIChatBox messages={messages} onSendMessage={send} isLoading={chat.isPending} height="580px" placeholder="Ask for review-ready help…" emptyStateMessage="Start with a focused question for this specialist." suggestedPrompts={prompts} className="rounded-none border-0 shadow-none" /></section></div></AppFrame>;
}

export function CallDesk() {
  const [leadLabel, setLeadLabel] = useState("");
  const [notes, setNotes] = useState("");
  const save = trpc.calls.saveNotes.useMutation({ onSuccess: () => { toast.success("Call notes saved for review."); setNotes(""); }, onError: error => toast.error(error.message) });
  return <AppFrame><PageHeading eyebrow="Live call desk" title="Keep the human in the conversation." description="Capture factual notes during a call, save them as a reviewable call session, and use the Conversation Coach for help without inventing outcomes." /><div className="mt-7 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><SectionTitle icon={Headphones} eyebrow="Call notes" title="Capture the real conversation." /><div className="mt-5 grid gap-4"><div><label className="text-sm font-bold text-[#102238]">Candidate or contact</label><Input value={leadLabel} onChange={event => setLeadLabel(event.target.value)} className="mt-2 h-11 rounded-xl" placeholder="e.g. Amara Daniels" /></div><div><label className="text-sm font-bold text-[#102238]">Factual live notes or transcript</label><Textarea value={notes} onChange={event => setNotes(event.target.value)} className="mt-2 min-h-60 rounded-xl" placeholder="Capture only what was said: interest, questions, objections, funding context, next steps, and timeline…" /></div><Button disabled={!leadLabel.trim() || !notes.trim() || save.isPending} onClick={() => save.mutate({ leadLabel, coachNotes: notes })} className="h-12 rounded-xl bg-[#102238] font-bold">Save reviewable call notes</Button></div></section><section className="rounded-[1.5rem] bg-[#e8f6ff] p-6"><div className="grid size-12 place-items-center rounded-2xl bg-[#57c4fb] text-[#102238]"><MessageSquareText size={21} /></div><h2 className="mt-5 font-display text-4xl font-bold tracking-[-.06em] text-[#102238]">Coach with evidence, not guesses.</h2><p className="mt-4 leading-7 text-slate-600">The Conversation Coach is set up to turn notes into concise guidance. It should never create commitments, objections, or programme facts that did not come from the actual conversation.</p><div className="mt-7 rounded-xl border border-[#bee7fb] bg-white/70 p-4"><p className="text-xs font-black uppercase tracking-[.13em] text-slate-400">Production voice path</p><p className="mt-2 text-sm leading-6 text-slate-600">The backend includes a secure transcription-ready call-session model. Connect a verified recording source and transcription service before using audio in live operations.</p></div></section></div></AppFrame>;
}

export function KnowledgeHub() {
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [url, setUrl] = useState(""); const [mode, setMode] = useState<"note" | "url">("note");
  const knowledge = trpc.knowledge.list.useQuery();
  const add = trpc.knowledge.add.useMutation({ onSuccess: () => { toast.success("Knowledge source added."); setTitle(""); setContent(""); setUrl(""); knowledge.refetch(); }, onError: error => toast.error(error.message) });
  return <AppFrame><PageHeading eyebrow="Knowledge control" title="Give agents only what they should know." description="Add approved programme information, policy notes, and trusted reference links before relying on agent guidance." /><div className="mt-7 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><SectionTitle icon={LibraryBig} eyebrow="New source" title="Add approved context." /><div className="mt-5 grid gap-4"><div className="flex gap-2"><Button variant={mode === "note" ? "default" : "outline"} onClick={() => setMode("note")} className={cn("rounded-lg", mode === "note" && "bg-[#102238]")}>Policy or programme note</Button><Button variant={mode === "url" ? "default" : "outline"} onClick={() => setMode("url")} className={cn("rounded-lg", mode === "url" && "bg-[#102238]")}>Reference link</Button></div><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="e.g. Cyber Security Programme — funding FAQ" className="h-11 rounded-xl" />{mode === "note" ? <Textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Paste approved programme information or policy text…" className="min-h-48 rounded-xl" /> : <Input value={url} onChange={event => setUrl(event.target.value)} placeholder="https://" className="h-11 rounded-xl" />}<Button disabled={!title.trim() || (mode === "note" ? !content.trim() : !url.trim()) || add.isPending} onClick={() => add.mutate({ title, sourceType: mode, ...(mode === "note" ? { content } : { sourceUrl: url }) })} className="h-12 rounded-xl bg-[#102238] font-bold">Add approved source</Button></div></section><section className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><SectionTitle icon={CheckCircle2} eyebrow="Approved knowledge" title="What the team has provided." /><div className="mt-5 space-y-3">{knowledge.isLoading ? <EmptyLine label="Loading knowledge sources…" /> : knowledge.data?.length ? knowledge.data.map(source => <article key={source.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-[#102238]">{source.title}</p><p className="mt-1 text-sm text-slate-500">{source.sourceType === "url" ? source.sourceUrl : "Internal knowledge note"}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-black uppercase tracking-wide text-emerald-700">{source.status}</span></div></article>) : <EmptyState icon={LibraryBig} title="No approved knowledge yet." text="Add Course2Career programme details and policy guidance before expecting agents to answer product questions." />}</div></section></div></AppFrame>;
}

export function ConnectionsPage() {
  const connections = trpc.integrations.list.useQuery();
  const profile = trpc.integrations.createProfile.useMutation({ onSuccess: () => { toast.success("Connection profile saved. Add its secrets through deployment settings."); connections.refetch(); }, onError: error => toast.error(error.message) });
  const cards = [
    { provider: "genie" as const, name: "Genie CRM", description: "Contacts, existing tasks, conversations, opportunities, and sequenced follow-up actions.", readiness: connections.data?.genie.configured, detail: "Genie is connected through the dedicated Playwright browser bridge, using the account login and reviewed page selectors. No Genie API key is required or stored." },
    { provider: "outlook" as const, name: "Outlook / Microsoft Graph", description: "Saved-message approval, email delivery, calendar scheduling, and change-notification subscriptions.", readiness: connections.data?.outlook.configured, detail: "Register a Microsoft Entra application with least-privilege mail and calendar permissions, then add the client credentials as secrets." },
    { provider: "genx" as const, name: "GenX model router", description: "Role-specific models for coaching, controlled drafting, knowledge guidance, and CRM context synthesis.", readiness: connections.data?.genx.ready, detail: "Provide the exact GenX chat-completions endpoint, API key, and default model identifier. The backend expects an OpenAI-style chat-completions response contract." },
  ];
  return <AppFrame><PageHeading eyebrow="Connections" title="Bring tools in with boundaries." description="Profiles explain the access each integration needs. Secrets stay server-side and connector execution remains disabled until credentials and endpoint contracts are verified." /><div className="mt-7 grid gap-5 xl:grid-cols-3">{cards.map(card => <section key={card.provider} className="flex flex-col rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><div className={cn("grid size-12 place-items-center rounded-2xl", card.readiness ? "bg-[#eef6d1] text-[#5d7500]" : "bg-slate-100 text-slate-500")}><Cable size={20} /></div><div className="mt-5 flex items-center justify-between gap-3"><h2 className="font-display text-2xl font-bold tracking-[-.055em] text-[#102238]">{card.name}</h2><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wide", card.readiness ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700")}>{card.readiness ? "Ready" : "Needs setup"}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">{card.description}</p><p className="mt-4 rounded-xl bg-[#f5f8fb] p-3 text-xs leading-5 text-slate-500">{card.detail}</p><Button variant="outline" className="mt-5 h-10 rounded-xl border-slate-300 font-bold" disabled={profile.isPending} onClick={() => profile.mutate({ provider: card.provider, displayName: `${card.name} production profile`, scopeSummary: card.description })}><Plus className="mr-2 size-4" />Save connection profile</Button></section>)}</div><div className="mt-6 rounded-[1.5rem] border border-[#cbe7f8] bg-[#eaf8ff] p-5 text-sm leading-6 text-slate-600"><strong className="text-[#102238]">Implementation status:</strong> the application has protected profiles, readiness checks, a GenX server adapter, and Microsoft Graph deployment guidance. It will not make external CRM, email, SMS, WhatsApp, or calendar changes until valid credentials and documented endpoint mappings are added.</div></AppFrame>;
}

function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="flex flex-col gap-4 border-b border-slate-200 pb-6 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#708400]">{eyebrow}</p><h1 className="mt-2 font-display text-4xl font-bold tracking-[-.07em] text-[#102238] sm:text-5xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600 sm:text-base">{description}</p></div>{action}</div>; }
function SectionTitle({ icon: Icon, eyebrow, title, dark = false }: { icon: typeof ShieldCheck; eyebrow: string; title: string; dark?: boolean }) { return <div className="flex items-center gap-3"><div className={cn("grid size-10 place-items-center rounded-xl", dark ? "bg-[#d8ff3e] text-[#102238]" : "bg-[#eef6d1] text-[#658000]")}><Icon size={18} /></div><div><p className={cn("text-[10px] font-black uppercase tracking-[.14em]", dark ? "text-white/45" : "text-slate-400")}>{eyebrow}</p><h2 className={cn("font-display text-2xl font-bold tracking-[-.05em]", dark ? "text-white" : "text-[#102238]")}>{title}</h2></div></div>; }
function Metric({ label, value, detail, icon: Icon, tone }: { label: string; value: number; detail: string; icon: typeof ShieldCheck; tone: "lime" | "sky" | "coral" }) { const tones = { lime: "bg-[#eef6d1] text-[#6e8700]", sky: "bg-[#e8f6ff] text-[#2382b9]", coral: "bg-[#fff0ed] text-[#d46057]" }; return <article className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 font-display text-4xl font-bold tracking-[-.07em] text-[#102238]">{value}</p></div><div className={cn("grid size-10 place-items-center rounded-xl", tones[tone])}><Icon size={18} /></div></div><p className="mt-3 text-xs text-slate-400">{detail}</p></article>; }
function EmptyState({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-[#fbfcfd] p-7 text-center"><div className="mx-auto grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-400"><Icon size={18} /></div><p className="mt-3 font-bold text-[#102238]">{title}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p></div>; }
function EmptyLine({ label }: { label: string }) { return <div className="rounded-xl bg-[#f5f8fb] px-4 py-8 text-center text-sm text-slate-500">{label}</div>; }
